<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); exit('Method not allowed.'); }
$user=Auth::requireUser();$id=(int)($_POST['id']??0);$pdo=Database::connection();
$art=$pdo->prepare('SELECT root_file FROM artworks WHERE id=:id AND user_id=:u LIMIT 1');$art->execute(['id'=>$id,'u'=>$user['id']]);$artwork=$art->fetch();if(!$artwork){http_response_code(404);exit('Artwork not found.');}
$allowed=$pdo->prepare('SELECT mockup_file FROM mockups WHERE user_id=:u AND artwork_file=:f');$allowed->execute(['u'=>$user['id'],'f'=>$artwork['root_file']]);$allowed=array_flip(array_map(fn($r)=>basename((string)$r['mockup_file']),$allowed->fetchAll()));
$files=array_values(array_filter(array_map('basename',explode(',',(string)($_POST['mockup_sequence']??'')))));if(count($files)<2 || array_diff($files,array_keys($allowed))){http_response_code(422);exit('La secuencia de mockups no es válida.');}
try{$result=(new MockupSequenceVideoService())->generate($files,['artworkId'=>$id]);$now=date('c');$update=$pdo->prepare('UPDATE social_video_workflows SET setup_suggestion_json=:s,setup_edited_json=:s2,final_concept_json=:m,status="video_ready",video_status="Video ready",video_url=:v,error="",updated_at=:n WHERE artwork_id=:a AND user_id=:u');$update->execute(['s'=>json_encode(['mockup_sequence'=>$files]),'s2'=>json_encode(['mockup_sequence'=>$files]),'m'=>json_encode(['video_metadata'=>$result]),'v'=>$result['file'],'n'=>$now,'a'=>$id,'u'=>$user['id']]);if($update->rowCount()===0){$pdo->prepare('INSERT INTO social_video_workflows (user_id,artwork_id,setup_suggestion_json,setup_edited_json,final_concept_json,status,video_status,video_url,error,created_at,updated_at) VALUES (:u,:a,:s,:s2,:m,"video_ready","Video ready",:v,"",:n,:n2)')->execute(['u'=>$user['id'],'a'=>$id,'s'=>json_encode(['mockup_sequence'=>$files]),'s2'=>json_encode(['mockup_sequence'=>$files]),'m'=>json_encode(['video_metadata'=>$result]),'v'=>$result['file'],'n'=>$now,'n2'=>$now]);}header('Location: social_video.php?id='.$id.'&video=ready');exit;}catch(Throwable $e){http_response_code(500);exit($e->getMessage());}
