<?php
declare(strict_types=1);

require_once __DIR__ . '/app/bootstrap.php';

$user = Auth::requireUser();
$pdo = Database::connection();

$id = max(0, (int)($_GET['id'] ?? 0));

if ($id <= 0) {
    http_response_code(404);
    die('Artwork ID is missing.');
}

// Fetch artwork and check ownership
$stmt = $pdo->prepare('SELECT * FROM artworks WHERE id = :id AND user_id = :user_id LIMIT 1');
$stmt->execute(['id' => $id, 'user_id' => $user['id']]);
$artwork = $stmt->fetch();

if (!$artwork) {
    http_response_code(404);
    die('Artwork not found or access denied.');
}

// 1. Read mockup-prompt-drafts JSON (with auto-generation fallback)
$draftsPath = __DIR__ . '/analysis/mockup-prompt-drafts/' . $id . '.prompt-drafts.json';
$draftsJson = null;
$autoGenerated = false;

if (!is_file($draftsPath)) {
    try {
        require_once __DIR__ . '/app/Services/MockupBranchPromptDraftBuilder.php';
        $builder = new MockupBranchPromptDraftBuilder();
        $draftsJson = $builder->buildForArtwork($id);
        $autoGenerated = true;
    } catch (Throwable $e) {
        Logger::log("MOCKUP_DRAFTS_AUTOGEN_ERROR for artwork_id: {$id}. Error: " . $e->getMessage(), 'error');
    }
} else {
    $content = file_get_contents($draftsPath);
    if ($content !== false) {
        $draftsJson = json_decode($content, true);
    }
}

if (!is_array($draftsJson)) {
    $draftsJson = null;
}

// 1.5 Read mockup-approved-prompts JSON if it exists
$approvedPath = __DIR__ . '/analysis/mockup-approved-prompts/' . $id . '.approved-prompts.json';
$approvedJson = null;
if (is_file($approvedPath)) {
    $approvedContent = file_get_contents($approvedPath);
    if ($approvedContent !== false) {
        $approvedJson = json_decode($approvedContent, true);
    }
}
if (!is_array($approvedJson)) {
    $approvedJson = null;
}

// 1.6 Retrieve flash alerts
Auth::start();
$flashSuccess = $_SESSION['flash_success'] ?? null;
$flashError = $_SESSION['flash_error'] ?? null;
unset($_SESSION['flash_success'], $_SESSION['flash_error']);

// Helpers for safety and formatting (wrapped to prevent re-declarations)
if (!function_exists('h')) {
    function h($v): string
    {
        return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
    }
}

if (!function_exists('map_bool')) {
    function map_bool($val): string
    {
        if ($val === true) {
            return 'Yes';
        }
        if ($val === false) {
            return 'No';
        }
        return 'Not detected';
    }
}

if (!function_exists('map_val')) {
    function map_val($val): string
    {
        if ($val === null || trim((string)$val) === '') {
            return 'Not detected';
        }
        return (string)$val;
    }
}

$promptDrafts = $draftsJson['prompt_drafts'] ?? [];
$warnings = $draftsJson['warnings'] ?? [];

$composer = new AdminPromptComposerPreview();
$adminPromptPlaceholderOk = true;
$adminPromptError = '';
try {
    $composerTemplate = PromptSettings::mockupFinalRequest();
    if (strpos($composerTemplate, '{{MOCKUP_CONTEXT_PROPOSAL}}') === false) {
        $adminPromptPlaceholderOk = false;
        $adminPromptError = 'The sovereign Admin V7 prompt in "Petición final de mockups" does not contain the required {{MOCKUP_CONTEXT_PROPOSAL}} placeholder.';
    }
} catch (Throwable $e) {
    $adminPromptPlaceholderOk = false;
    $adminPromptError = $e->getMessage();
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Mockup Prompt Drafts - The Artwork Curator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <style>
        .specs-panel {
            background: var(--surface);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 24px;
            margin-bottom: 30px;
            box-shadow: var(--shadow);
        }
        .specs-grid {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            gap: 16px;
        }
        .spec-item {
            background: var(--surface-soft);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 12px 16px;
        }
        .spec-item span {
            display: block;
            font-size: 10px;
            font-weight: 600;
            text-transform: uppercase;
            color: var(--muted);
            letter-spacing: 0.05em;
            margin-bottom: 4px;
        }
        .spec-item code {
            font-family: monospace;
            font-size: 12px;
            color: var(--ink);
            word-break: break-all;
        }

        .drafts-list {
            display: flex;
            flex-direction: column;
            gap: 30px;
            margin-bottom: 30px;
        }
        .draft-card {
            background: var(--surface);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 26px;
            box-shadow: var(--shadow);
        }
        
        .draft-header {
            border-bottom: 1px dashed var(--line);
            padding-bottom: 16px;
            margin-bottom: 20px;
        }
        .draft-header-meta {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 8px;
        }
        .draft-header h3 {
            margin: 0;
            font-family: var(--font-serif);
            font-size: 26px;
            color: var(--ink);
            line-height: 1.2;
        }
        .draft-header h4 {
            margin: 4px 0 0 0;
            font-size: 14px;
            font-weight: 500;
            color: var(--muted);
            font-style: italic;
        }

        .resolved-view-box {
            background: rgba(154, 123, 86, 0.03);
            border: 1px solid rgba(154, 123, 86, 0.15);
            border-radius: var(--radius);
            padding: 14px 18px;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 15px;
        }
        .resolved-view-box p {
            margin: 0;
            font-size: 13px;
            color: var(--ink);
        }
        .resolved-view-box p strong {
            font-weight: 600;
        }
        .resolved-view-box code {
            font-family: monospace;
            font-size: 12px;
        }

        .prompt-blocks-grid {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            gap: 16px;
            margin-bottom: 20px;
        }
        .block-card {
            background: var(--surface-soft);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 14px;
        }
        .block-card.full-width {
            grid-column: span 2;
        }
        .block-card h5 {
            margin: 0 0 6px 0;
            font-size: 10px;
            font-weight: 700;
            text-transform: uppercase;
            color: var(--muted);
            letter-spacing: 0.05em;
        }
        .block-card p {
            margin: 0;
            font-size: 12px;
            line-height: 1.5;
            color: var(--ink);
        }

        .final-prompt-container {
            border-top: 1px dashed var(--line);
            padding-top: 20px;
        }
        .final-prompt-container h4 {
            margin: 0 0 10px 0;
            font-size: 12px;
            text-transform: uppercase;
            font-weight: 700;
            color: var(--ink);
            letter-spacing: 0.05em;
        }
        .final-prompt-textarea {
            width: 100%;
            height: 220px;
            font-family: monospace;
            font-size: 12px;
            line-height: 1.6;
            padding: 12px;
            border: 1px solid var(--line);
            border-radius: var(--radius);
            background: var(--surface-soft);
            color: var(--ink);
            resize: vertical;
        }

        .badge {
            font-size: 10px;
            font-weight: 600;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            padding: 4px 8px;
            border-radius: 3px;
            background: var(--accent-light);
            color: var(--accent);
            border: 1px solid rgba(154, 123, 86, 0.2);
            display: inline-block;
        }
        .badge.danger {
            background: #FFF5F5;
            color: var(--danger);
            border-color: rgba(166, 60, 60, 0.2);
        }
        .badge.success {
            background: #E6FFFA;
            color: #234E52;
            border-color: rgba(35, 78, 82, 0.2);
        }
        .badge.warning {
            background: #FFFDF5;
            color: #8C6D1F;
            border-color: rgba(140, 109, 31, 0.2);
        }

        @media (max-width: 900px) {
            .prompt-blocks-grid {
                grid-template-columns: 1fr;
            }
            .block-card.full-width {
                grid-column: span 1;
            }
            .specs-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
<div class="app-shell">
    <?php include __DIR__ . '/sidebar.php'; ?>

    <main class="main-area">
        <header class="app-header">
            <a class="user-chip" href="account.php"><?= h($user['email']) ?></a>
        </header>

        <div class="alert-strip">
            Mockup Prompt Draft Review: Read-only inspection of structured text prompt drafts segmenting artwork specifications.
        </div>

        <div class="workspace">
            <div class="workspace-header">
                <div>
                    <h1>Mockup Prompt Drafts</h1>
                    <p>Fase 2.1 technical prompt review panel showing the generated drafts without calling Vertex/Gemini.</p>
                </div>
                <div class="topbar-actions">
                    <button
                        id="btn-regenerate-proposals"
                        type="button"
                        onclick="regenerateProposals(<?= (int)$id ?>, this)"
                        style="
                            display: inline-flex;
                            align-items: center;
                            gap: 6px;
                            padding: 8px 16px;
                            background: #7C3626;
                            color: #fff;
                            border: none;
                            border-radius: var(--radius);
                            font-size: 13px;
                            font-weight: 600;
                            cursor: pointer;
                            letter-spacing: 0.02em;
                            transition: background 0.15s, opacity 0.15s;
                        "
                        onmouseover="this.style.background='#9A4330'"
                        onmouseout="this.style.background='#7C3626'"
                        title="Regenerate all mockup context proposals for this artwork using the current ADMIN master prompt. Does not repeat core analysis or root artwork generation."
                    >↺ Regenerate Mockup Proposals</button>
                    <a class="button-link" href="mockup_combinations_review.php?id=<?= (int)$id ?>">Review Combinations</a>
                    <a class="button-link secondary" href="mockup_branches_review.php?id=<?= (int)$id ?>">Back to Branch Contexts</a>
                    <a class="button-link secondary" href="artwork_details.php?id=<?= (int)$id ?>">Artwork Details</a>
                </div>
            </div>

            <?php if ($flashSuccess): ?>
                <div class="notice success">
                    <strong>Success:</strong> <?= h($flashSuccess) ?>
                </div>
            <?php endif; ?>

            <?php if ($flashError): ?>
                <div class="notice error">
                    <strong>Error:</strong> <?= h($flashError) ?>
                </div>
            <?php endif; ?>

            <?php if ($draftsJson === null): ?>
                <div class="notice error">
                    <strong>Warning:</strong> The mockup prompt drafts JSON could not be loaded or auto-generated. Please make sure the CORE JSON and mockup branches JSON files are present.
                </div>
            <?php elseif ($autoGenerated): ?>
                <div class="notice" style="border-left-color: var(--accent); background: rgba(154, 123, 86, 0.05);">
                    <strong>System Auto-generation:</strong> The prompt drafts JSON file was not found, so it was successfully generated and saved to disk.
                </div>
            <?php endif; ?>

            <?php if (!empty($warnings)): ?>
                <div class="notice warning">
                    <strong>Builder Warnings:</strong>
                    <ul style="margin: 5px 0 0 20px; padding: 0;">
                        <?php foreach ($warnings as $warning): ?>
                            <li><?= h($warning) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <!-- SPECIFICATIONS PANEL -->
            <div class="specs-panel">
                <div class="specs-grid">
                    <div class="spec-item">
                        <span>Artwork ID</span>
                        <code><?= (int)$id ?></code>
                    </div>
                    <div class="spec-item">
                        <span>Source Core JSON</span>
                        <code><?= h($draftsJson['source_core_json'] ?? "analysis/core/{$id}.core.json") ?></code>
                    </div>
                    <div class="spec-item">
                        <span>Source Branches JSON</span>
                        <code><?= h($draftsJson['source_branches_json'] ?? "analysis/mockup-branches/{$id}.branches.json") ?></code>
                    </div>
                    <div class="spec-item">
                        <span>Output Prompt Drafts JSON</span>
                        <code>analysis/mockup-prompt-drafts/<?= (int)$id ?>.prompt-drafts.json</code>
                    </div>
                </div>
            </div>

            <?php if ($approvedJson !== null): ?>
                <!-- APPROVED PROMPTS SUMMARY -->
                <div class="specs-panel" style="border-left: 4px solid #234E52; background: rgba(35, 78, 82, 0.02); margin-bottom: 30px;">
                    <h3 style="margin-top: 0; margin-bottom: 12px; font-family: var(--font-serif); color: #234E52; font-size: 18px;">✓ Approved Prompts Summary</h3>
                    <div class="specs-grid">
                        <div class="spec-item">
                            <span>Approved At</span>
                            <code><?= h($approvedJson['approved_at'] ?? 'N/A') ?></code>
                        </div>
                        <div class="spec-item">
                            <span>Approved Prompt Count</span>
                            <code><?= count($approvedJson['approved_prompts'] ?? []) ?></code>
                        </div>
                        <div class="spec-item">
                            <span>Approved Draft Indexes</span>
                            <code>
                                <?php 
                                $idxs = [];
                                foreach ($approvedJson['approved_prompts'] ?? [] as $ap) {
                                    $idxs[] = $ap['draft_index'] ?? $ap['branch_index'];
                                }
                                echo h(implode(', ', $idxs));
                                ?>
                            </code>
                        </div>
                        <div class="spec-item">
                            <span>Context Names</span>
                            <code>
                                <?php 
                                $names = [];
                                foreach ($approvedJson['approved_prompts'] ?? [] as $ap) {
                                    $names[] = $ap['context_name'] ?? 'Untitled';
                                }
                                echo h(implode(', ', $names));
                                ?>
                            </code>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <!-- DRAFTS DETAIL LIST -->
            <div class="section-heading">
                <div>
                    <h2>Segmented Prompt Drafts</h2>
                    <p>Read-only text prompts generated for each normalized branch direction</p>
                </div>
            </div>

            <div class="drafts-list">
                <?php if (!empty($promptDrafts)): ?>
                    <?php foreach ($promptDrafts as $idx => $draft): ?>
                        <?php 
                        $blocks = $draft['prompt_blocks'] ?? [];
                        $view = $draft['resolved_root_view'] ?? [];
                        ?>
                        <div class="draft-card">
                            <div class="draft-header">
                                <div class="draft-header-meta">
                                    <span class="badge" style="background: var(--surface-soft); color: var(--ink); font-weight: 700;">Draft <?= $idx + 1 ?></span>
                                    <span class="badge success">Inspection Ready</span>
                                </div>
                                <h3><?= h($draft['context_name'] ?? 'Untitled') ?></h3>
                                <h4><?= h($draft['source_branch_label'] ?? '') ?></h4>
                            </div>

                            <div class="resolved-view-box">
                                <p><strong>Resolved Root View:</strong> <code><?= h($view['view_type'] ?? 'fallback') ?></code></p>
                                <p><strong>Filename:</strong> <code><?= h($view['file'] ?? 'None') ?></code></p>
                                <p>
                                    <strong>Fallback Used:</strong> 
                                    <?php if (!empty($view['fallback_used'])): ?>
                                        <span class="badge warning" style="font-size: 8px; padding: 2px 5px;">Yes (Fallback View)</span>
                                    <?php else: ?>
                                        <span class="badge success" style="font-size: 8px; padding: 2px 5px;">No (Exact Match)</span>
                                    <?php endif; ?>
                                </p>
                            </div>

                            <div class="prompt-blocks-grid">
                                <div class="block-card">
                                    <h5>Artwork Reference</h5>
                                    <p><?= h($blocks['artwork_reference'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Physical Artwork Spec</h5>
                                    <p><?= h($blocks['physical_artwork_spec'] ?? '') ?></p>
                                </div>
                                <div class="block-card full-width">
                                    <h5>Scene Context</h5>
                                    <p><?= h($blocks['scene_context'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Artwork Placement</h5>
                                    <p><?= h($blocks['artwork_placement'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Camera Direction</h5>
                                    <p><?= h($blocks['camera_direction'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Scale Direction</h5>
                                    <p><?= h($blocks['scale_direction'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Lighting Direction</h5>
                                    <p><?= h($blocks['lighting_direction'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Material Direction</h5>
                                    <p><?= h($blocks['material_direction'] ?? '') ?></p>
                                </div>
                                <div class="block-card">
                                    <h5>Commercial Direction</h5>
                                    <p><?= h($blocks['commercial_direction'] ?? '') ?></p>
                                </div>
                                <div class="block-card full-width" style="border-left: 3px solid var(--danger);">
                                    <h5>Negative Prompt</h5>
                                    <p><?= h($blocks['negative_prompt'] ?? '') ?></p>
                                </div>
                            </div>

                             <div class="final-prompt-container">
                                 <h4>Assembled Final Prompt</h4>
                                 <textarea class="final-prompt-textarea" readonly onclick="this.select()"><?= h($draft['final_prompt'] ?? '') ?></textarea>

                                 <div style="margin-top: 15px; text-align: right;">
                                     <?php 
                                     $isApproved = false;
                                     if ($approvedJson !== null && isset($approvedJson['approved_prompts'])) {
                                         foreach ($approvedJson['approved_prompts'] as $ap) {
                                             if (($ap['draft_index'] ?? null) === $draft['branch_index']) {
                                                 $isApproved = true;
                                                 break;
                                             }
                                         }
                                     }
                                     ?>
                                     <?php if ($isApproved): ?>
                                         <span class="badge success" style="font-size: 11px; padding: 8px 12px; border-color: #234E52;">✓ Approved & Saved</span>
                                     <?php else: ?>
                                         <a class="button-link" style="background: #1a73e8; color: #fff; border-color: #1a73e8; font-weight: 600; padding: 8px 16px; border-radius: 4px; display: inline-block; text-decoration: none;" href="approve_mockup_prompt_draft.php?artwork_id=<?= (int)$id ?>&draft_index=<?= (int)$draft['branch_index'] ?>">Approve This Prompt Draft</a>
                                     <?php endif; ?>
                                 </div>
                             </div>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div style="text-align: center; padding: 40px; border: 1px dashed var(--line); border-radius: var(--radius); background: var(--surface);">
                        <p style="color: var(--muted); margin: 0;">No prompt drafts populated.</p>
                    </div>
                <?php endif; ?>
            </div>

            <?php
            $stmtContexts = $pdo->prepare('SELECT * FROM mockup_contexts WHERE artwork_id = :artwork_id ORDER BY id ASC');
            $stmtContexts->execute(['artwork_id' => $id]);
            $dbContextProposals = $stmtContexts->fetchAll();
            ?>

            <!-- PHASE 2.3 PANEL: ADMIN V7 COMPOSED PROMPT TEST -->
            <div class="section-heading" style="margin-top: 50px; display: flex; justify-content: space-between; align-items: center; width: 100%; gap: 20px;">
                <div>
                    <h2>Phase 2.3 — Admin V7 Composed Prompt Test</h2>
                    <p>Controlled one-by-one mockup generation using sovereign Admin V7 prompt template with inserted context proposal block.</p>
                </div>
                <div style="display: flex; gap: 10px; align-items: center;">
                    <button class="button-link"
                            id="btn-regenerate-proposals"
                            style="background: #d93025; color: #fff; border-color: #d93025; font-weight: 600; padding: 10px 20px; border-radius: 4px; display: inline-block; cursor: pointer; white-space: nowrap;"
                            onclick="regenerateProposals(<?= (int)$id ?>, this)">
                        Regenerate Mockup Proposals
                    </button>
                    <?php if (!empty($dbContextProposals)): ?>
                        <?php
                        $first6 = array_slice($dbContextProposals, 0, 6);
                        $first6ContextIds = array_map(fn($c) => (int)$c['id'], $first6);
                        ?>
                        <button class="button-link"
                                id="btn-generate-6"
                                data-context-ids="<?= h(json_encode($first6ContextIds)) ?>"
                                style="background: #1a73e8; color: #fff; border-color: #1a73e8; font-weight: 600; padding: 10px 20px; border-radius: 4px; display: inline-block; cursor: pointer; white-space: nowrap;"
                                onclick="generate6Mockups(<?= (int)$id ?>, this)">
                            Generate 6 Reviewed Mockups
                        </button>
                    <?php endif; ?>
                </div>
            </div>

            <div id="gen-6-progress-panel" style="display: none; background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius); padding: 20px; margin-top: 20px; box-shadow: var(--shadow);">
                <h3 style="margin-top: 0; font-size: 16px; color: var(--ink);">Generate 6 Reviewed Mockups Progress</h3>
                <div id="gen-6-status" style="font-weight: bold; margin-bottom: 15px; font-size: 14px;"></div>
                <div id="gen-6-logs" style="display: flex; flex-direction: column; gap: 10px; font-size: 13px;"></div>
            </div>

            <?php if (!$adminPromptPlaceholderOk): ?>
                <div class="notice error">
                    <strong>Admin V7 Prompt Configuration Error:</strong> <?= h($adminPromptError) ?>
                </div>
            <?php endif; ?>

            <div class="drafts-list" style="margin-top: 20px;">
                <?php if (!empty($dbContextProposals)): ?>
                    <?php foreach ($dbContextProposals as $pIdx => $cProp): ?>
                        <?php
                        $cJson = json_decode((string)($cProp['context_json'] ?? ''), true);
                        if (!is_array($cJson)) { $cJson = []; }
                        
                        $proposalName = $cProp['context_name'] ?? 'Proposal ' . ($pIdx + 1);
                        
                        // Parse values to show
                        $cameraViewVal = $cJson['camera_view'] ?? '';
                        $cameraDistanceVal = $cJson['camera_distance'] ?? '';
                        
                        // Build context block preview
                        $cComposer = new AdminPromptComposerPreview();
                        $composedPreview = '';
                        $composedError = '';
                        try {
                            $composedPreview = $cComposer->compose($cProp);
                        } catch (Throwable $ex) {
                            $composedError = $ex->getMessage();
                        }
                        
                        // Get the parsed context proposal block using reflection or simple extraction
                        $materialsVal = $cJson['materials'] ?? '';
                        if (is_array($materialsVal)) { $materialsVal = implode(', ', $materialsVal); }
                        
                        $proposalBlockString = "MOCKUP CONTEXT PROPOSAL:\n"
                            . "Use the following context only as subordinated scene data. These values define the\n"
                            . "environment, placement, lighting and camera direction, but they do not override the\n"
                            . "artwork fidelity rules, scale rules, human figure policy, camera proximity rules, or\n"
                            . "negative directives stated in the admin master prompt.\n\n"
                            . "* Scene Name: " . trim((string)($cProp['context_name'] ?? '')) . "\n"
                            . "* Purpose: " . trim((string)($cJson['context_role'] ?? '')) . "\n"
                            . "* Scene Description: " . trim((string)($cJson['mockup_prompt'] ?? '')) . "\n"
                            . "* Materials: " . trim((string)$materialsVal) . "\n"
                            . "* Lighting: " . trim((string)($cJson['lighting'] ?? '')) . "\n"
                            . "* Placement: " . trim((string)($cJson['placement'] ?? '')) . "\n"
                            . "* Camera View: " . trim((string)$cameraViewVal) . "\n"
                            . "* Camera Distance: " . trim((string)$cameraDistanceVal) . "\n"
                            . "* Camera Notes: " . trim((string)($cJson['camera_angle_notes'] ?? ''));
                        ?>
                        <div class="draft-card" style="border: 1px solid #1a73e8; background: rgba(26, 115, 232, 0.01);">
                            <div class="draft-header">
                                <div class="draft-header-meta">
                                    <span class="badge" style="background: #1a73e8; color: #fff; font-weight: 700;">Proposal <?= $pIdx + 1 ?></span>
                                    <span class="badge success" style="background: rgba(26, 115, 232, 0.05); color: #1a73e8; border-color: rgba(26, 115, 232, 0.1);">Admin V7 Flow</span>
                                </div>
                                <h3><?= h($proposalName) ?></h3>
                                <h4>From <code>mockup_contexts</code> DB table (Row ID: <?= (int)$cProp['id'] ?>)</h4>
                            </div>

                            <div style="margin-bottom: 20px;">
                                <h4 style="margin: 0 0 10px 0; font-size: 13px; font-weight: 600; text-transform: uppercase; color: var(--muted);">1. Context Proposal Data (Read-Only)</h4>
                                <div class="specs-grid" style="grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; margin-bottom: 12px;">
                                    <div class="spec-item" style="padding: 8px 12px;">
                                        <span>Scene Name</span>
                                        <code style="font-size: 11px;"><?= h($cProp['context_name'] ?? '') ?></code>
                                    </div>
                                    <div class="spec-item" style="padding: 8px 12px;">
                                        <span>Purpose</span>
                                        <code style="font-size: 11px;"><?= h($cJson['context_role'] ?? '') ?></code>
                                    </div>
                                    <div class="spec-item" style="padding: 8px 12px;">
                                        <span>Lighting</span>
                                        <code style="font-size: 11px;"><?= h($cJson['lighting'] ?? '') ?></code>
                                    </div>
                                    <div class="spec-item" style="padding: 8px 12px;">
                                        <span>Placement</span>
                                        <code style="font-size: 11px;"><?= h($cJson['placement'] ?? '') ?></code>
                                    </div>
                                    <div class="spec-item" style="padding: 8px 12px;">
                                        <span>Camera View</span>
                                        <code style="font-size: 11px; font-weight: bold; color: #1a73e8;"><?= h($cameraViewVal) ?></code>
                                    </div>
                                    <div class="spec-item" style="padding: 8px 12px;">
                                        <span>Camera Distance</span>
                                        <code style="font-size: 11px; font-weight: bold; color: #1a73e8;"><?= h($cameraDistanceVal) ?></code>
                                    </div>
                                </div>
                                <div class="spec-item" style="padding: 8px 12px; margin-bottom: 10px;">
                                    <span>Scene Description</span>
                                    <p style="margin: 0; font-size: 12px; color: var(--ink); line-height: 1.4;"><?= h($cJson['mockup_prompt'] ?? '') ?></p>
                                </div>
                            </div>

                            <div style="display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; border-top: 1px dashed var(--line); padding-top: 20px;">
                                <div>
                                    <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px;">
                                        <h4 style="margin: 0; font-size: 12px; text-transform: uppercase; font-weight: 700; color: var(--ink);">Context Proposal Block Text</h4>
                                        <button class="button-link secondary" style="padding: 3px 8px; font-size: 11px;" onclick="copyTextToClipboard(this, <?= $pIdx ?>)">Copy Context Proposal</button>
                                    </div>
                                    <textarea id="proposal-block-<?= $pIdx ?>" class="final-prompt-textarea" style="height: 180px; font-size: 11px;" readonly><?= h($proposalBlockString) ?></textarea>
                                </div>

                                <div>
                                    <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px;">
                                        <h4 style="margin: 0; font-size: 12px; text-transform: uppercase; font-weight: 700; color: var(--ink);">Composed Final Admin Prompt Preview</h4>
                                        <button class="button-link secondary" style="padding: 3px 8px; font-size: 11px;" onclick="copyComposedToClipboard(this, <?= $pIdx ?>)">Copy Final Admin Prompt</button>
                                    </div>
                                    <?php if ($composedError): ?>
                                        <div style="height: 180px; padding: 12px; border: 1px solid var(--danger); background: #FFF5F5; color: var(--danger); font-size: 12px; border-radius: var(--radius); overflow-y: auto;">
                                            Error: <?= h($composedError) ?>
                                        </div>
                                    <?php else: ?>
                                        <textarea id="composed-block-<?= $pIdx ?>" class="final-prompt-textarea" style="height: 180px; font-size: 11px;" readonly><?= h($composedPreview) ?></textarea>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div style="margin-top: 20px; text-align: right; border-top: 1px dashed var(--line); padding-top: 15px;">
                                <div id="gen-status-<?= (int)$cProp['id'] ?>" style="display: inline-block; margin-right: 15px; font-size: 12px; vertical-align: middle;"></div>
                                <button class="button-link" 
                                        style="background: #1a73e8; color: #fff; border-color: #1a73e8; font-weight: 600; padding: 10px 20px; border-radius: 4px; display: inline-block; vertical-align: middle; cursor: pointer;" 
                                        onclick="generateOneMockup(<?= (int)$id ?>, <?= (int)$cProp['id'] ?>, this)"
                                        <?php if (!$adminPromptPlaceholderOk || $composedError): ?>disabled style="opacity: 0.5; cursor: not-allowed;"<?php endif; ?>>
                                    Generate One Mockup From This Final Admin Prompt
                                </button>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div style="text-align: center; padding: 40px; border: 1px dashed var(--line); border-radius: var(--radius); background: var(--surface);">
                        <p style="color: var(--muted); margin: 0;">No mockup contexts found in database for this artwork.</p>
                    </div>
                <?php endif; ?>
            </div>

            <!-- JAVASCRIPT LOGIC FOR COPY AND GENERATION -->
            <script>
            function copyTextToClipboard(btn, index) {
                const txt = document.getElementById('proposal-block-' + index).value;
                navigator.clipboard.writeText(txt).then(() => {
                    const originalText = btn.textContent;
                    btn.textContent = 'Copied!';
                    btn.style.background = '#234E52';
                    btn.style.color = '#fff';
                    setTimeout(() => {
                        btn.textContent = originalText;
                        btn.style.background = '';
                        btn.style.color = '';
                    }, 1500);
                });
            }

            function copyComposedToClipboard(btn, index) {
                const txt = document.getElementById('composed-block-' + index).value;
                navigator.clipboard.writeText(txt).then(() => {
                    const originalText = btn.textContent;
                    btn.textContent = 'Copied!';
                    btn.style.background = '#234E52';
                    btn.style.color = '#fff';
                    setTimeout(() => {
                        btn.textContent = originalText;
                        btn.style.background = '';
                        btn.style.color = '';
                    }, 1500);
                });
            }

            function generateOneMockup(artworkId, contextId, btn) {
                if (!confirm('Are you sure you want to generate one mockup from this context using the sovereign Admin V7 prompt?')) {
                    return;
                }

                // Validate IDs before sending
                if (!artworkId || !contextId || artworkId <= 0 || contextId <= 0) {
                    alert('Error: artwork_id or context_id is missing. Cannot generate.');
                    console.error('generateOneMockup called with invalid IDs:', { artworkId, contextId });
                    return;
                }

                const statusDiv = document.getElementById('gen-status-' + contextId);
                btn.disabled = true;
                btn.style.opacity = '0.7';
                const originalBtnText = btn.textContent;
                btn.textContent = 'Generating...';
                statusDiv.innerHTML = '<span style="color: var(--muted); font-weight: bold;">[Vertex Bridge calling...] Please wait.</span>';

                const formData = new FormData();
                formData.append('artwork_id', String(artworkId));
                formData.append('context_id', String(contextId));

                console.log('[generateOneMockup] POST artwork_id=' + artworkId + ' context_id=' + contextId);

                fetch('generate_one_mockup_from_composed_admin_prompt.php', {
                    method: 'POST',
                    body: formData
                })
                .then(function(response) {
                    const httpStatus = response.status;
                    return response.text().then(function(rawText) {
                        console.log('[generateOneMockup] HTTP ' + httpStatus + ' raw response:', rawText);
                        let parsed = null;
                        try {
                            parsed = JSON.parse(rawText);
                        } catch (parseErr) {
                            console.error('[generateOneMockup] JSON parse failed. Raw response was:', rawText);
                            throw new Error('Server returned a non-JSON response (HTTP ' + httpStatus + '). Check PHP logs. Preview: ' + rawText.substring(0, 300));
                        }
                        return { status: httpStatus, body: parsed };
                    });
                })
                .then(function(res) {
                    if (res.status === 200 && res.body.ok) {
                        const auditParts = res.body.audit_file ? res.body.audit_file.split('/') : [];
                        const auditFilename = auditParts[auditParts.length - 1] || '';
                        statusDiv.innerHTML = '<span style="color: #234E52; font-weight: bold;">✓ Success! Mockup generated.</span> ' +
                            '<a href="view_mockup_file.php?mockup_id=' + encodeURIComponent(res.body.mockup_id) + '" target="_blank" style="margin-left: 8px; font-weight: bold; text-decoration: underline; color: #1a73e8;">View Mockup</a> | ' +
                            '<a href="view_mockup_generation_audit.php?id=' + encodeURIComponent(res.body.mockup_id) + '" target="_blank" style="font-weight: bold; text-decoration: underline; color: #1a73e8;">View Audit JSON</a>';
                        btn.textContent = 'Generated!';
                        btn.style.background = '#234E52';
                        btn.style.borderColor = '#234E52';
                    } else {
                        const errMsg = (res.body && res.body.error) ? res.body.error : ('HTTP ' + res.status + ' — unknown error');
                        statusDiv.innerHTML = '<span style="color: var(--danger); font-weight: bold;">Error: ' + errMsg + '</span>';
                        console.error('[generateOneMockup] Endpoint error response:', res.body);
                        btn.disabled = false;
                        btn.style.opacity = '1';
                        btn.textContent = originalBtnText;
                    }
                })
                .catch(function(err) {
                    const errMsg = err && err.message ? err.message : String(err);
                    statusDiv.innerHTML = '<span style="color: var(--danger); font-weight: bold;">Generation failed: ' + errMsg + '</span>';
                    btn.disabled = false;
                    btn.style.opacity = '1';
                    btn.textContent = originalBtnText;
                    console.error('[generateOneMockup] Caught error:', err);
                });
            }

            async function generate6Mockups(artworkId, btn) {
                const contextIds = JSON.parse(btn.getAttribute('data-context-ids') || '[]');
                if (contextIds.length === 0) {
                    alert('No context proposals available to generate.');
                    return;
                }

                if (!confirm(`Are you sure you want to generate mockups for the first ${contextIds.length} reviewed context proposals?`)) {
                    return;
                }

                btn.disabled = true;
                btn.style.opacity = '0.7';
                const originalText = btn.textContent;
                btn.textContent = 'Generating Batch...';

                const progressPanel = document.getElementById('gen-6-progress-panel');
                const statusDiv = document.getElementById('gen-6-status');
                const logsDiv = document.getElementById('gen-6-logs');

                progressPanel.style.display = 'block';
                statusDiv.innerHTML = '<span style="color: var(--muted);">Starting generation round...</span>';
                logsDiv.innerHTML = '';

                let successCount = 0;
                let failCount = 0;

                for (let i = 0; i < contextIds.length; i++) {
                    const contextId = contextIds[i];
                    const stepNum = i + 1;
                    statusDiv.innerHTML = `Generating proposal ${stepNum} of ${contextIds.length}...`;

                    // Create log line placeholder
                    const logLine = document.createElement('div');
                    logLine.style.padding = '8px 12px';
                    logLine.style.background = 'var(--surface-soft)';
                    logLine.style.border = '1px solid var(--line)';
                    logLine.style.borderRadius = '4px';
                    logLine.innerHTML = `<strong>Proposal ID #${contextId}:</strong> <span style="color: var(--muted);">Calling Vertex Bridge...</span>`;
                    logsDiv.appendChild(logLine);

                    // Update individual button/status div if they exist on page
                    const indStatusDiv = document.getElementById('gen-status-' + contextId);
                    if (indStatusDiv) {
                        indStatusDiv.innerHTML = '<span style="color: var(--muted); font-weight: bold;">[Vertex Bridge calling...] Please wait.</span>';
                    }

                    try {
                        const formData = new FormData();
                        formData.append('artwork_id', String(artworkId));
                        formData.append('context_id', String(contextId));

                        const response = await fetch('generate_one_mockup_from_composed_admin_prompt.php', {
                            method: 'POST',
                            body: formData
                        });

                        const httpStatus = response.status;
                        const rawText = await response.text();
                        console.log(`[generate6Mockups] Proposal ${contextId} HTTP ${httpStatus} raw:`, rawText);

                        let parsed = null;
                        try {
                            parsed = JSON.parse(rawText);
                        } catch (parseErr) {
                            throw new Error(`Server returned a non-JSON response (HTTP ${httpStatus}).`);
                        }

                        if (httpStatus === 200 && parsed.ok) {
                            successCount++;
                            const logHtml = `<strong>Proposal ID #${contextId}:</strong> <span style="color: #234E52; font-weight: bold;">✓ Success! Mockup #${parsed.mockup_id} generated.</span> ` +
                                `<a href="view_mockup_file.php?mockup_id=${encodeURIComponent(parsed.mockup_id)}" target="_blank" style="margin-left: 8px; font-weight: bold; text-decoration: underline; color: #1a73e8;">View Mockup</a> | ` +
                                `<a href="view_mockup_generation_audit.php?id=${encodeURIComponent(parsed.mockup_id)}" target="_blank" style="font-weight: bold; text-decoration: underline; color: #1a73e8;">View Audit JSON</a>`;
                            logLine.innerHTML = logHtml;

                            if (indStatusDiv) {
                                indStatusDiv.innerHTML = logHtml;
                            }
                        } else {
                            failCount++;
                            const errMsg = (parsed && parsed.error) ? parsed.error : `HTTP ${httpStatus}`;
                            const logHtml = `<strong>Proposal ID #${contextId}:</strong> <span style="color: var(--danger); font-weight: bold;">✗ Failed: ${errMsg}</span>`;
                            logLine.innerHTML = logHtml;

                            if (indStatusDiv) {
                                indStatusDiv.innerHTML = logHtml;
                            }
                        }
                    } catch (err) {
                        failCount++;
                        const errMsg = err && err.message ? err.message : String(err);
                        const logHtml = `<strong>Proposal ID #${contextId}:</strong> <span style="color: var(--danger); font-weight: bold;">✗ Failed: ${errMsg}</span>`;
                        logLine.innerHTML = logHtml;

                        if (indStatusDiv) {
                            indStatusDiv.innerHTML = logHtml;
                        }
                    }
                }

                statusDiv.innerHTML = `<span style="color: #234E52; font-weight: bold;">✓ Completed!</span> ${successCount} generated successfully, ${failCount} failed.`;
                btn.textContent = originalText;
                btn.disabled = false;
                btn.style.opacity = '1';
            }

            function regenerateProposals(artworkId, btn) {
                const confirmMsg = "This will regenerate all mockup context proposals for this artwork using the current ADMIN master prompt. Existing mockup proposals for this artwork will be replaced or marked obsolete. Existing generated image files will not be deleted. Continue?";
                if (!confirm(confirmMsg)) {
                    return;
                }

                if (!artworkId || artworkId <= 0) {
                    alert('Error: artwork_id is missing or invalid.');
                    return;
                }

                btn.disabled = true;
                btn.style.opacity = '0.7';
                const originalText = btn.textContent;
                btn.textContent = 'Regenerating...';

                const formData = new FormData();
                formData.append('artwork_id', String(artworkId));

                console.log('[regenerateProposals] POST artwork_id=' + artworkId);

                fetch('regenerate_mockup_proposals.php', {
                    method: 'POST',
                    body: formData
                })
                .then(function(response) {
                    const httpStatus = response.status;
                    return response.text().then(function(rawText) {
                        console.log('[regenerateProposals] HTTP ' + httpStatus + ' raw response:', rawText);
                        let parsed = null;
                        try {
                            parsed = JSON.parse(rawText);
                        } catch (parseErr) {
                            console.error('[regenerateProposals] JSON parse failed. Raw response was:', rawText);
                            throw new Error('Server returned a non-JSON response (HTTP ' + httpStatus + ').');
                        }
                        return { status: httpStatus, body: parsed };
                    });
                })
                .then(function(res) {
                    if (res.status === 200 && res.body.ok) {
                        alert(res.body.message || 'Success! Mockup proposals regenerated.');
                        window.location.reload();
                    } else {
                        const errMsg = (res.body && res.body.error) ? res.body.error : ('HTTP ' + res.status + ' — unknown error');
                        alert('Error: ' + errMsg);
                        btn.disabled = false;
                        btn.style.opacity = '1';
                        btn.textContent = originalText;
                    }
                })
                .catch(function(err) {
                    const errMsg = err && err.message ? err.message : String(err);
                    alert('Regeneration failed: ' + errMsg);
                    btn.disabled = false;
                    btn.style.opacity = '1';
                    btn.textContent = originalText;
                    console.error('[regenerateProposals] Caught error:', err);
                });
            }
            </script>

        </div>
    </main>
</div>
</body>
</html>
