<?php
declare(strict_types=1);

require_once __DIR__ . '/app/bootstrap.php';

$user = Auth::requireUser();
$pdo = Database::connection();

$id = max(0, (int)($_GET['id'] ?? 0));

if ($id <= 0) {
    http_response_code(404);
    die('Artwork ID is missing.');
}

// Fetch artwork and check ownership
$stmt = $pdo->prepare('SELECT * FROM artworks WHERE id = :id AND user_id = :user_id LIMIT 1');
$stmt->execute(['id' => $id, 'user_id' => $user['id']]);
$artwork = $stmt->fetch();

if (!$artwork) {
    http_response_code(404);
    die('Artwork not found or access denied.');
}

// 1. Read mockup-branches JSON (with auto-generation fallback)
$branchesPath = __DIR__ . '/analysis/mockup-branches/' . $id . '.branches.json';
$branchesJson = null;
$autoGenerated = false;

if (!is_file($branchesPath)) {
    try {
        require_once __DIR__ . '/app/Services/MockupBranchContextBuilder.php';
        $builder = new MockupBranchContextBuilder();
        $branchesJson = $builder->buildForArtwork($id);
        $autoGenerated = true;
    } catch (Throwable $e) {
        Logger::log("MOCKUP_BRANCHES_AUTOGEN_ERROR for artwork_id: {$id}. Error: " . $e->getMessage(), 'error');
    }
} else {
    $content = file_get_contents($branchesPath);
    if ($content !== false) {
        $branchesJson = json_decode($content, true);
    }
}

if (!is_array($branchesJson)) {
    $branchesJson = null;
}

// Helpers for safety and formatting
if (!function_exists('h')) {
    function h($v): string
    {
        return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
    }
}

if (!function_exists('map_bool')) {
    function map_bool($val): string
    {
        if ($val === true) {
            return 'Yes';
        }
        if ($val === false) {
            return 'No';
        }
        return 'Not detected';
    }
}

if (!function_exists('map_array')) {
    function map_array($arr): string
    {
        if (!is_array($arr) || empty($arr)) {
            return 'None';
        }
        return implode(', ', array_map('h', $arr));
    }
}

if (!function_exists('map_val')) {
    function map_val($val): string
    {
        if ($val === null || trim((string)$val) === '') {
            return 'Not detected';
        }
        return (string)$val;
    }
}

// Resolve view strategy details
$branches = $branchesJson['branches'] ?? [];
$strategy = !empty($branches) ? ($branches[0]['root_view_strategy'] ?? []) : [];
if (empty($strategy) && $branchesJson === null) {
    // If no JSON was loaded, construct a minimal database fallback strategy
    $frontalFile = null;
    $threeQuarterLeftFile = null;
    $threeQuarterRightFile = null;
    try {
        $candStmt = $pdo->prepare("SELECT file_name, view_type FROM root_artwork_candidates WHERE artwork_id = :id");
        $candStmt->execute(['id' => $id]);
        foreach ($candStmt->fetchAll() as $row) {
            $vt = (string)$row['view_type'];
            if ($vt === 'frontal') {
                $frontalFile = basename((string)$row['file_name']);
            } elseif ($vt === 'three-quarter-left') {
                $threeQuarterLeftFile = basename((string)$row['file_name']);
            } elseif ($vt === 'three-quarter-right') {
                $threeQuarterRightFile = basename((string)$row['file_name']);
            }
        }
    } catch (Throwable $e) {}

    $fallbackFile = $artwork['root_file'] ? basename((string)$artwork['root_file']) : ($frontalFile ?? $threeQuarterLeftFile ?? $threeQuarterRightFile ?? null);
    $strategy = [
        'frontal' => $frontalFile,
        'three_quarter_left' => $threeQuarterLeftFile,
        'three_quarter_right' => $threeQuarterRightFile,
        'fallback' => $fallbackFile
    ];
}

// Resolver for displaying resolved active view files
if (!function_exists('resolve_active_view_file')) {
    function resolve_active_view_file(array $branch, array $strategy): array
    {
        $camera = strtolower(trim((string)($branch['mockup_direction']['camera_bias'] ?? '')));
        $file = null;
        $type = 'fallback';

        if (str_contains($camera, 'frontal')) {
            $file = $strategy['frontal'] ?? null;
            $type = 'frontal';
        } elseif (str_contains($camera, 'left') || str_contains($camera, 'oblique')) {
            $file = $strategy['three_quarter_left'] ?? $strategy['three_quarter_right'] ?? null;
            $type = $strategy['three_quarter_left'] ? 'three_quarter_left' : ($strategy['three_quarter_right'] ? 'three_quarter_right' : 'fallback');
        } elseif (str_contains($camera, 'right')) {
            $file = $strategy['three_quarter_right'] ?? null;
            $type = 'three_quarter_right';
        }

        if ($file === null) {
            $file = $strategy['fallback'] ?? null;
            $type = 'fallback';
        }

        return ['file' => $file, 'type' => $type];
    }
}

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Mockup Branch Contexts - The Artwork Curator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <style>
        .specs-panel {
            background: var(--surface);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 24px;
            margin-bottom: 30px;
            box-shadow: var(--shadow);
        }
        .specs-grid {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            gap: 16px;
            margin-bottom: 20px;
        }
        .spec-item {
            background: var(--surface-soft);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 12px 16px;
        }
        .spec-item span {
            display: block;
            font-size: 10px;
            font-weight: 600;
            text-transform: uppercase;
            color: var(--muted);
            letter-spacing: 0.05em;
            margin-bottom: 4px;
        }
        .spec-item code {
            font-family: monospace;
            font-size: 12px;
            color: var(--ink);
            word-break: break-all;
        }
        
        .strategy-section {
            margin-top: 20px;
            border-top: 1px dashed var(--line);
            padding-top: 20px;
        }
        .strategy-grid {
            display: grid;
            grid-template-columns: repeat(4, minmax(0, 1fr));
            gap: 12px;
        }
        .strat-card {
            background: var(--surface);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 12px 14px;
            text-align: center;
        }
        .strat-card span {
            display: block;
            font-size: 9px;
            font-weight: 700;
            text-transform: uppercase;
            color: var(--muted);
            margin-bottom: 6px;
        }
        .strat-card code {
            font-family: monospace;
            font-size: 11px;
            word-break: break-all;
        }
        
        .branches-list {
            display: flex;
            flex-direction: column;
            gap: 24px;
            margin-bottom: 30px;
        }
        .branch-item-card {
            background: var(--surface);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 26px;
            box-shadow: var(--shadow);
            display: grid;
            grid-template-columns: 1.2fr 1fr;
            gap: 30px;
        }
        .branch-info-panel h3 {
            margin: 0 0 10px 0;
            font-family: var(--font-serif);
            font-size: 26px;
            color: var(--ink);
            line-height: 1.2;
        }
        .branch-info-panel h4 {
            margin: 0 0 16px 0;
            font-size: 14px;
            font-weight: 500;
            color: var(--muted);
            font-style: italic;
        }
        .branch-info-panel p {
            margin: 0 0 20px 0;
            font-size: 13px;
            line-height: 1.6;
            color: var(--ink);
            opacity: 0.9;
        }
        
        .branch-params-grid {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            gap: 12px;
            background: var(--surface-soft);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 16px;
        }
        .param-field span {
            display: block;
            font-size: 9px;
            font-weight: 700;
            text-transform: uppercase;
            color: var(--muted);
            margin-bottom: 2px;
        }
        .param-field strong {
            font-size: 12px;
            color: var(--ink);
        }
        
        .view-strategy-box {
            border: 1px solid var(--line);
            border-radius: var(--radius);
            padding: 20px;
            background: rgba(154, 123, 86, 0.01);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }
        .view-strategy-box h4 {
            margin: 0 0 12px 0;
            font-size: 11px;
            text-transform: uppercase;
            font-weight: 700;
            color: var(--ink);
            letter-spacing: 0.05em;
        }
        .resolved-view-details {
            margin-bottom: 16px;
        }
        .resolved-view-details p {
            margin: 4px 0;
            font-size: 13px;
        }
        
        .badge {
            font-size: 10px;
            font-weight: 600;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            padding: 4px 8px;
            border-radius: 3px;
            background: var(--accent-light);
            color: var(--accent);
            border: 1px solid rgba(154, 123, 86, 0.2);
            display: inline-block;
        }
        .badge.danger {
            background: #FFF5F5;
            color: var(--danger);
            border-color: rgba(166, 60, 60, 0.2);
        }
        .badge.success {
            background: #E6FFFA;
            color: #234E52;
            border-color: rgba(35, 78, 82, 0.2);
        }
        
        @media (max-width: 900px) {
            .branch-item-card {
                grid-template-columns: 1fr;
                gap: 20px;
            }
            .specs-grid,
            .strategy-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
<div class="app-shell">
    <?php include __DIR__ . '/sidebar.php'; ?>

    <main class="main-area">
        <header class="app-header">
            <a class="user-chip" href="account.php"><?= h($user['email']) ?></a>
        </header>

        <div class="alert-strip">
            Mockup Branch Context Review: Read-only inspection of normalized branches, root view strategies and camera biases.
        </div>

        <div class="workspace">
            <div class="workspace-header">
                <div>
                    <h1>Mockup Branch Contexts</h1>
                    <p>Fase 2.0 technical review panel showing the structured branches mapping.</p>
                </div>
                <div class="topbar-actions">
                    <a class="button-link secondary" href="core_review.php?id=<?= (int)$id ?>">Back to Core Review</a>
                    <a class="button-link secondary" href="mockup_prompt_drafts_review.php?id=<?= (int)$id ?>">View Mockup Prompt Drafts</a>
                    <a class="button-link secondary" href="artwork_details.php?id=<?= (int)$id ?>">Artwork Details</a>
                </div>
            </div>

            <?php if ($branchesJson === null): ?>
                <div class="notice error">
                    <strong>Warning:</strong> The mockup branches JSON could not be loaded or auto-generated. Please make sure the CORE JSON file is present at `analysis/core/<?= (int)$id ?>.core.json`.
                </div>
            <?php elseif ($autoGenerated): ?>
                <div class="notice" style="border-left-color: var(--accent); background: rgba(154, 123, 86, 0.05);">
                    <strong>System Auto-generation:</strong> The branches JSON file was not found, so it was successfully generated and saved to disk.
                </div>
            <?php endif; ?>

            <!-- SPECIFICATIONS PANEL -->
            <div class="specs-panel">
                <div class="specs-grid">
                    <div class="spec-item">
                        <span>Artwork ID</span>
                        <code><?= (int)$id ?></code>
                    </div>
                    <div class="spec-item">
                        <span>Core Schema Version</span>
                        <code><?= h($branchesJson['core_schema_version'] ?? '1.1') ?></code>
                    </div>
                    <div class="spec-item">
                        <span>Source Core JSON</span>
                        <code><?= h($branchesJson['source_core_json'] ?? "analysis/core/{$id}.core.json") ?></code>
                    </div>
                    <div class="spec-item">
                        <span>Output Branches JSON</span>
                        <code>analysis/mockup-branches/<?= (int)$id ?>.branches.json</code>
                    </div>
                </div>

                <div class="strategy-section">
                    <label style="margin-top: 0; margin-bottom: 8px;">Active Root View Strategy Mappings</label>
                    <div class="strategy-grid">
                        <div class="strat-card" style="<?= ($strategy['fallback'] ?? null) === ($strategy['frontal'] ?? null) ? 'border-color: var(--accent); background: var(--accent-light);' : '' ?>">
                            <span>Frontal View File</span>
                            <code><?= h(basename((string)($strategy['frontal'] ?? 'Missing'))) ?></code>
                        </div>
                        <div class="strat-card" style="<?= ($strategy['fallback'] ?? null) === ($strategy['three_quarter_left'] ?? null) ? 'border-color: var(--accent); background: var(--accent-light);' : '' ?>">
                            <span>Three-quarter Left File</span>
                            <code><?= h(basename((string)($strategy['three_quarter_left'] ?? 'Missing'))) ?></code>
                        </div>
                        <div class="strat-card" style="<?= ($strategy['fallback'] ?? null) === ($strategy['three_quarter_right'] ?? null) ? 'border-color: var(--accent); background: var(--accent-light);' : '' ?>">
                            <span>Three-quarter Right File</span>
                            <code><?= h(basename((string)($strategy['three_quarter_right'] ?? 'Missing'))) ?></code>
                        </div>
                        <div class="strat-card" style="border-left: 3px solid var(--accent); background: var(--surface-soft);">
                            <span>Resolved Fallback File</span>
                            <code><?= h(basename((string)($strategy['fallback'] ?? 'None resolved'))) ?></code>
                        </div>
                    </div>
                </div>
            </div>

            <!-- BRANCHES DETAIL LIST -->
            <div class="section-heading">
                <div>
                    <h2>Structured Context Branches</h2>
                    <p>View strategy and parsed parameters per curatorial direction</p>
                </div>
            </div>

            <div class="branches-list">
                <?php if (!empty($branches)): ?>
                    <?php foreach ($branches as $idx => $branch): ?>
                        <?php 
                        $dir = $branch['mockup_direction'] ?? [];
                        $viewRes = resolve_active_view_file($branch, $strategy);
                        $fileEx = $viewRes['file'] && is_file(RESULTS_DIR . DIRECTORY_SEPARATOR . $viewRes['file']);
                        ?>
                        <div class="branch-item-card">
                            <div class="branch-info-panel">
                                <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px;">
                                    <span class="badge" style="background: var(--surface-soft); color: var(--ink); font-weight: 700;">Branch <?= $idx + 1 ?></span>
                                    <span class="badge success">Normalized Context</span>
                                </div>
                                <h3><?= h($branch['source_title'] ?? 'Untitled') ?></h3>
                                <h4><?= h($branch['source_subtitle'] ?? '') ?></h4>
                                <p><?= h($branch['source_description'] ?? '') ?></p>

                                <div class="branch-params-grid">
                                    <div class="param-field">
                                        <span>Atmosphere</span>
                                        <strong><?= h(map_val($dir['atmosphere'] ?? null)) ?></strong>
                                    </div>
                                    <div class="param-field">
                                        <span>Lighting Bias</span>
                                        <strong><?= h(map_val($dir['lighting_bias'] ?? null)) ?></strong>
                                    </div>
                                    <div class="param-field">
                                        <span>Space Character</span>
                                        <strong><?= h(map_val($dir['space_character'] ?? null)) ?></strong>
                                    </div>
                                    <div class="param-field">
                                        <span>Camera Bias</span>
                                        <strong><?= h(map_val($dir['camera_bias'] ?? null)) ?></strong>
                                    </div>
                                    <div class="param-field" style="grid-column: span 2;">
                                        <span>Material Affinity</span>
                                        <strong><?= h(map_array($dir['material_affinity'] ?? null)) ?></strong>
                                    </div>
                                    <div class="param-field" style="grid-column: span 2;">
                                        <span>Commercial Positioning</span>
                                        <strong><?= h(map_val($dir['commercial_positioning'] ?? null)) ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="view-strategy-box">
                                <div>
                                    <h4>Root View Resolution Strategy</h4>
                                    <div class="resolved-view-details">
                                        <p><strong>Resolved View Type:</strong> <code><?= h($viewRes['type']) ?></code></p>
                                        <p><strong>Resolved Filename:</strong> <code><?= h(basename((string)($viewRes['file'] ?? 'None'))) ?></code></p>
                                        <p><strong>File Status:</strong> 
                                            <?php if ($fileEx): ?>
                                                <span class="badge success" style="font-size: 8px; padding: 2px 5px;">Present on disk</span>
                                            <?php else: ?>
                                                <span class="badge danger" style="font-size: 8px; padding: 2px 5px;">File Missing</span>
                                            <?php endif; ?>
                                        </p>
                                    </div>
                                </div>

                                <div style="text-align: center; border: 1px dashed var(--line); border-radius: var(--radius); padding: 10px; background: var(--surface-soft);">
                                    <?php if ($fileEx): ?>
                                        <a href="media.php?file=<?= rawurlencode((string)$viewRes['file']) ?>" target="_blank">
                                            <img src="media.php?file=<?= rawurlencode((string)$viewRes['file']) ?>" style="max-width: 100%; max-height: 140px; border-radius: 2px; border: 1px solid var(--line); display: block; margin: 0 auto;">
                                        </a>
                                    <?php else: ?>
                                        <span style="font-size: 11px; color: var(--muted);">No reference image preview</span>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div style="text-align: center; padding: 40px; border: 1px dashed var(--line); border-radius: var(--radius); background: var(--surface);">
                        <p style="color: var(--muted); margin: 0;">No context branches populated.</p>
                    </div>
                <?php endif; ?>
            </div>

        </div>
    </main>
</div>
</body>
</html>
