<?php
declare(strict_types=1);
require_once __DIR__.'/app/bootstrap.php';
$user=Auth::requireUser();Auth::start();$userId=(int)$user['id'];$id=max(0,(int)($_GET['id']??$_POST['id']??0));$pdo=Database::connection();$drafts=new MockupPinterestDraftService($pdo);$pinterest=new PinterestIntegrationService($pdo);$error=(string)($_SESSION['pinterest_publish_error']??'');$notice=(string)($_SESSION['pinterest_publish_notice']??'');unset($_SESSION['pinterest_publish_error'],$_SESSION['pinterest_publish_notice']);$boards=[];$sections=[];$preview=[];$blockers=[];$connection=null;
try{
    $draft=$drafts->draft($id,$userId);$purpose=(string)$draft['purpose'];$connection=$pinterest->connection($userId,$purpose);
    if(($connection['status']??'')==='connected'){$boards=$pinterest->boards($userId,$purpose);if(($draft['board_id']??'')!=='')$sections=$pinterest->sections($userId,$purpose,(string)$draft['board_id']);}
    if($_SERVER['REQUEST_METHOD']==='POST'){
        if(!hash_equals((string)($_SESSION['pinterest_board_csrf']??''),(string)($_POST['csrf']??'')))throw new RuntimeException('The board selection session expired.');
        $action=(string)($_POST['action']??'select_board');if($action==='save_crop'){$draft=$drafts->saveCrop($id,$userId,(float)($_POST['crop_x']??.5),(float)($_POST['crop_y']??.5),(float)($_POST['crop_zoom']??1));$notice='Vertical Pinterest crop saved. Nothing was published.';}elseif($action==='select_section'){$draft=$drafts->selectSection($id,$userId,(string)($_POST['section_id']??''),$sections);$notice='Section saved. Nothing was published.';}else{$draft=$drafts->selectBoard($id,$userId,(string)($_POST['board_id']??''),$boards);$notice='Board saved. Nothing was published.';$sections=$pinterest->sections($userId,$purpose,(string)$draft['board_id']);}
    }
    $recommended=$drafts->recommendBoard($draft,$boards);
    $base=rtrim(app_env('APP_PUBLIC_URL',''),'/');$imageUrl=$base!==''?$base.'/pinterest_draft_media.php?token='.rawurlencode((string)($draft['media_token']??'')):'';
    $preview=['board_id'=>(string)($draft['board_id']??''),'link'=>(string)$draft['destination_url'],'title'=>(string)$draft['title'],'description'=>(string)$draft['description'],'alt_text'=>(string)$draft['alt_text'],'media_source'=>['source_type'=>'image_url','url'=>$imageUrl,'is_standard'=>true]];if(($draft['board_section_id']??'')!=='')$preview['board_section_id']=$draft['board_section_id'];
    $blockers=[];if(($draft['variant_file']??'')==='')$blockers[]='Save a reviewed vertical 2:3 crop first.';if(($connection['status']??'')!=='connected')$blockers[]='The selected Pinterest identity is not connected in this environment.';if(($draft['board_id']??'')==='')$blockers[]='A real Pinterest board has not been selected.';if(!str_starts_with($base,'https://'))$blockers[]='APP_PUBLIC_URL is not a public HTTPS URL.';if(app_env('PINTEREST_DRAFT_PUBLIC_MEDIA_ENABLED','false')!=='true')$blockers[]='A public draft-media route has not been enabled and verified.';if(app_env('PINTEREST_LIVE_PUBLISH_ENABLED','false')!=='true')$blockers[]='Live Pinterest publishing is disabled by environment policy.';
}catch(Throwable $e){$error=$error!==''?$error:$e->getMessage();$draft=$draft??null;$recommended=null;}
$_SESSION['pinterest_board_csrf']=bin2hex(random_bytes(24));$_SESSION['pinterest_live_csrf']=bin2hex(random_bytes(24));function pdh($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pinterest Draft Review</title><link rel="stylesheet" href="style.css"><style>.draft-grid{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:22px}.draft-card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:20px}.crop-editor{max-width:400px;margin:auto}.crop-editor canvas{display:block;width:100%;aspect-ratio:2/3;background:#111;cursor:grab;touch-action:none}.crop-editor canvas:active{cursor:grabbing}.crop-controls{display:grid;gap:10px;margin-top:12px}.board-selector{border:0;padding:0;margin:14px 0}.board-selector legend{font-weight:600;margin-bottom:10px}.board-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.board-option{display:flex;align-items:flex-start;gap:9px;border:1px solid var(--line);border-radius:10px;padding:11px;cursor:pointer;background:var(--surface-soft)}.board-option:has(input:checked){border-color:#9b6750;box-shadow:0 0 0 1px #9b6750;background:#fff}.board-option input{margin-top:3px}.board-option span{line-height:1.25}.board-option small{display:block;color:#9b6750;margin-top:3px}.api-preview{white-space:pre-wrap;overflow:auto;font:12px/1.5 Consolas,monospace;background:var(--surface-soft);padding:14px}.blocker-list{color:#8a3a32}.disabled-action{opacity:.55;cursor:not-allowed}@media(max-width:850px){.draft-grid{grid-template-columns:1fr}}@media(max-width:480px){.board-options{grid-template-columns:1fr}}</style></head><body><div class="app-shell"><?php include __DIR__.'/sidebar.php';?><main class="main-area"><div class="workspace"><div class="workspace-header"><div><h1>Pinterest Draft #<?=$id?></h1><p>Review the exact mockup content and coordinate it with a Pinterest board.</p></div><?php if($draft):?><a class="button-link secondary" href="viewer.php?id=<?=(int)$draft['mockup_id']?>">← Viewer</a><?php endif;?></div>
<?php if($error):?><div class="notice error"><?=pdh($error)?></div><?php endif;?><?php if($notice):?><div class="notice success"><?=pdh($notice)?></div><?php endif;?>
<?php if($draft):?><div class="draft-grid"><section class="draft-card"><h2>Vertical Pinterest crop</h2><form method="post" class="crop-editor" id="cropForm"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="csrf" value="<?=pdh($_SESSION['pinterest_board_csrf'])?>"><input type="hidden" name="action" value="save_crop"><input type="hidden" name="crop_x" id="cropX" value="<?=pdh($draft['crop_x']??.5)?>"><input type="hidden" name="crop_y" id="cropY" value="<?=pdh($draft['crop_y']??.5)?>"><canvas id="cropCanvas" width="400" height="600" data-source="media.php?file=<?=rawurlencode(basename((string)$draft['mockup_file']))?>"></canvas><div class="crop-controls"><label>Zoom <input id="cropZoom" name="crop_zoom" type="range" min="1" max="3" step="0.01" value="<?=pdh($draft['crop_zoom']??1)?>"></label><button type="button" class="button-link secondary" id="cropReset">Reset framing</button><button type="submit" class="button-link secondary">Save Pinterest crop</button></div></form><p><small>Fixed vertical 2:3 frame. Drag to reposition; the original mockup is never changed.</small></p><h2><?=pdh($draft['title'])?></h2><p><?=nl2br(pdh($draft['description']))?></p><p><strong>Destination</strong><br><?=pdh($draft['destination_url'])?></p></section><aside class="draft-card"><p><strong>Identity:</strong> <?=pdh($draft['purpose'])?></p><p><strong>Suggested board theme:</strong> <?=pdh($draft['board_suggestion'])?></p>
<?php if($boards):?><form method="post"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="csrf" value="<?=pdh($_SESSION['pinterest_board_csrf'])?>"><input type="hidden" name="action" value="select_board"><fieldset class="board-selector"><legend>Choose a Pinterest board</legend><div class="board-options"><?php foreach($boards as $board):$boardId=(string)($board['id']??'');$isRecommended=($recommended['id']??null)===($board['id']??null);?><label class="board-option"><input type="radio" name="board_id" value="<?=pdh($boardId)?>" <?=($draft['board_id']??'')===$boardId?'checked':''?> required><span><?=pdh($board['name']??'Untitled')?><?php if($isRecommended):?><small>Recommended</small><?php endif;?></span></label><?php endforeach;?></div></fieldset><button class="button-link secondary" type="submit">Save board selection</button></form><?php if(($draft['board_id']??'')!==''):?><form method="post"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="csrf" value="<?=pdh($_SESSION['pinterest_board_csrf'])?>"><input type="hidden" name="action" value="select_section"><label>Board section (optional)</label><select name="section_id"><option value="">No section</option><?php foreach($sections as $section):?><option value="<?=pdh($section['id']??'')?>" <?=($draft['board_section_id']??'')===($section['id']??'')?'selected':''?>><?=pdh($section['name']??'Untitled')?></option><?php endforeach;?></select><button class="button-link secondary" type="submit">Save section</button></form><?php endif;?><?php else:?><div class="notice">The <?=pdh($draft['purpose'])?> Pinterest account is not connected in this environment. The draft is safe and can be coordinated after connection.</div><?php endif;?>
<p><strong>Status:</strong> <?=pdh($draft['status'])?></p><?php if(($draft['external_url']??'')!==''):?><p><a href="<?=pdh($draft['external_url'])?>" target="_blank" rel="noopener">View published Pin</a></p><?php endif;?></aside></div><section class="draft-card" style="margin-top:22px"><h2>Final API Preview</h2><pre class="api-preview"><?=pdh(json_encode($preview,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre><h3>Publication blockers</h3><?php if($blockers):?><ul class="blocker-list"><?php foreach($blockers as $blocker):?><li><?=pdh($blocker)?></li><?php endforeach;?></ul><label><input type="checkbox" disabled> I reviewed this exact payload and approve one Pin.</label><p><button class="button-link primary disabled-action" type="button" disabled>Publish one Pin</button></p><?php else:?><div class="notice success">All technical checks passed.</div><form method="post" action="pinterest_draft_publish.php"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="csrf" value="<?=pdh($_SESSION['pinterest_live_csrf'])?>"><label><input type="checkbox" name="confirm" value="yes" required> I reviewed this exact payload and approve one Pin.</label><p><button class="button-link primary" name="action" value="publish">Publish one Pin</button></p></form><?php endif;?><small>One explicit confirmation creates at most one Pin.</small></section><script>(()=>{const c=document.getElementById('cropCanvas');if(!c)return;const ctx=c.getContext('2d'),img=new Image(),x=document.getElementById('cropX'),y=document.getElementById('cropY'),z=document.getElementById('cropZoom');let drag=false,lastX=0,lastY=0;function draw(){if(!img.naturalWidth)return;const zoom=+z.value,scale=Math.max(c.width/img.naturalWidth,c.height/img.naturalHeight)*zoom,cw=c.width/scale,ch=c.height/scale,left=(img.naturalWidth-cw)*(+x.value),top=(img.naturalHeight-ch)*(+y.value);ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,left,top,cw,ch,0,0,c.width,c.height)}img.onload=draw;img.src=c.dataset.source;z.addEventListener('input',draw);c.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;x.value=Math.max(0,Math.min(1,+x.value-(e.clientX-lastX)/c.clientWidth));y.value=Math.max(0,Math.min(1,+y.value-(e.clientY-lastY)/c.clientHeight));lastX=e.clientX;lastY=e.clientY;draw()});c.addEventListener('pointerup',()=>drag=false);document.getElementById('cropReset').addEventListener('click',()=>{x.value=.5;y.value=.5;z.value=1;draw()})})();</script><?php endif;?></div></main></div></body></html>
