<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';
$user = Auth::requireUser();
$service = new PublicationService(Database::connection());
$publications = $service->listForUser((int)$user['id']);
$counts = ['draft'=>0,'published'=>0];
foreach ($publications as $row) { $counts[$row['status']] = ($counts[$row['status']] ?? 0) + 1; }
function psh($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Publishing Studio</title><link rel="stylesheet" href="style.css"><style>
.studio-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:22px}.studio-stat,.publication-card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow)}.studio-stat{padding:18px}.studio-stat strong{display:block;font-size:28px}.publication-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px}.publication-card{overflow:hidden}.publication-card img{width:100%;aspect-ratio:16/10;object-fit:cover;background:var(--surface-soft)}.publication-card-body{padding:16px}.publication-card h2{font-size:20px;margin:0 0 5px}.publication-meta{font-size:12px;color:var(--muted);margin:0 0 14px}.status-pill{display:inline-block;padding:4px 8px;border:1px solid var(--line);border-radius:999px;font-size:10px;text-transform:uppercase;letter-spacing:.06em}.status-pill.published{border-color:#79a083;color:#356643;background:#f0f7f1}.empty-studio{padding:42px;text-align:center;background:var(--surface);border:1px dashed var(--line);border-radius:var(--radius)}@media(max-width:700px){.studio-summary{grid-template-columns:1fr}}
</style></head><body><div class="app-shell"><?php include __DIR__.'/sidebar.php'; ?><main class="main-area"><header class="app-header"><a class="user-chip" href="account.php"><?=psh($user['email'])?></a></header><div class="workspace">
<div class="workspace-header"><div><h1>Publishing Studio</h1><p>Prepare, publish and manage artwork presentations across every channel.</p></div><a class="button-link primary" href="mockups.php">Choose a mockup</a></div>
<div class="studio-summary"><div class="studio-stat"><span>All publications</span><strong><?=count($publications)?></strong></div><div class="studio-stat"><span>Drafts</span><strong><?=(int)($counts['draft']??0)?></strong></div><div class="studio-stat"><span>Published</span><strong><?=(int)($counts['published']??0)?></strong></div></div>
<?php if(!$publications):?><div class="empty-studio"><h2>No publications yet</h2><p>Open a mockup in the Viewer and choose <strong>Publish</strong> to begin.</p><a class="button-link primary" href="mockups.php">Open Mockup Album</a></div><?php else:?><div class="publication-grid"><?php foreach($publications as $publication):?><article class="publication-card"><?php if($publication['source_image_file']):?><img src="media.php?file=<?=rawurlencode(basename((string)$publication['source_image_file']))?>" alt=""><?php endif;?><div class="publication-card-body"><span class="status-pill <?=psh($publication['status'])?>"><?=psh($publication['status'])?></span><h2><?=psh($publication['title'] ?: 'Untitled artwork')?></h2><p class="publication-meta"><?=(int)$publication['item_count']?> mockups · <?=psh($publication['visibility'])?></p><a class="button-link secondary" href="prepare_publication.php?id=<?=(int)$publication['id']?>"><?= $publication['status']==='published' ? 'Manage publication' : 'Continue editing' ?></a><?php if($publication['status']==='published'):?> <a class="button-link secondary" target="_blank" href="public_artwork.php?slug=<?=rawurlencode((string)$publication['slug'])?>">View landing</a><?php endif;?></div></article><?php endforeach;?></div><?php endif;?>
</div></main></div></body></html>
