<?php
declare(strict_types=1);

return [
    'schema' => 'mockup_context_families.v1',
    'families' => [
        'minimal_white_gallery' => [
            'family_id' => 'minimal_white_gallery',
            'world_id' => 'minimal_contemporary_world',
            'label' => 'Minimal White Gallery',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['white_gallery', 'minimal', 'clean', 'commercial'],
            'architecture_language' => 'clean contemporary gallery planes, controlled proportions, calm openings',
            'wall_language' => 'matte off-white or mineral white wall, subtle texture, no signage',
            'floor_language' => 'polished concrete, pale wood, or quiet stone floor',
            'ceiling_language' => 'simple ceiling plane with discreet gallery lighting',
            'furniture_density' => 'none_or_very_low',
            'decorative_density' => 'very_low',
            'material_temperature' => 'neutral_to_cool',
            'lighting_bias' => 'soft_gallery_daylight_or_controlled_track_light',
            'scale_behavior' => 'physically_plausible_artwork_first',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['commercially_usable_scale', 'no_monumental_atrium', 'no_heroic_scale', 'no_architectural_spectacle', 'no_pets', 'no_crowds', 'no_labels', 'no_artwork_substitution'],
            'negative_context_terms' => ['monumental atrium', 'heroic scale', 'architectural spectacle', 'busy gallery', 'crowd', 'art fair signage', 'pet', 'animal'],
        ],
        'contemporary_concrete_collector' => [
            'family_id' => 'contemporary_concrete_collector',
            'world_id' => 'minimal_contemporary_world',
            'label' => 'Contemporary Concrete Collector',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['concrete', 'collector', 'architectural', 'minimal'],
            'architecture_language' => 'restrained concrete interior with architectural edges and measured depth',
            'wall_language' => 'smooth concrete, limewash, or mineral plaster wall',
            'floor_language' => 'concrete or stone floor with sober reflectance',
            'ceiling_language' => 'flat architectural ceiling, beams allowed only if quiet',
            'furniture_density' => 'low',
            'decorative_density' => 'low',
            'material_temperature' => 'neutral_mineral',
            'lighting_bias' => 'lateral soft daylight or warm architectural light',
            'scale_behavior' => 'commercially_usable_concrete_context_not_monumental',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_simple_concrete_room_enlarged', 'no_monumental_atrium', 'no_heroic_scale', 'no_pets', 'no_scale_distortion', 'no_canvas_warp', 'no_artwork_substitution'],
            'negative_context_terms' => ['monumental atrium', 'heroic concrete hall', 'architectural spectacle', 'cozy clutter', 'busy decor', 'pet', 'animal', 'crowd'],
        ],
        'european_palazzo_gallery' => [
            'family_id' => 'european_palazzo_gallery',
            'world_id' => 'historical_european_world',
            'label' => 'European Palazzo Gallery',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['palazzo', 'historical', 'european', 'collector'],
            'architecture_language' => 'old European room with tall proportions, arches, moulding, or stone details kept restrained',
            'wall_language' => 'aged plaster, limewash, warm stone, or muted historic color',
            'floor_language' => 'stone, terrazzo, parquet, or old timber floor',
            'ceiling_language' => 'tall ceiling, beams or moulding allowed if secondary',
            'furniture_density' => 'low_to_medium',
            'decorative_density' => 'low_to_medium',
            'material_temperature' => 'warm_historical',
            'lighting_bias' => 'golden_late_day_or_soft_window_light',
            'scale_behavior' => 'artwork_primary_with_architectural_gravity',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_period_costume_scene', 'no_pets', 'no_museum_crowds', 'no_artwork_substitution'],
            'negative_context_terms' => ['royal event', 'costume drama', 'crowd', 'pet', 'animal'],
        ],
        'old_townhouse_collector_room' => [
            'family_id' => 'old_townhouse_collector_room',
            'world_id' => 'historical_european_world',
            'label' => 'Old Townhouse Collector Room',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['townhouse', 'collector', 'library', 'european'],
            'architecture_language' => 'townhouse interior with old walls, discreet books or architectural memory',
            'wall_language' => 'deep muted paint, aged plaster, or paneled wall',
            'floor_language' => 'old wood, parquet, or muted rug over timber',
            'ceiling_language' => 'residential historic ceiling with quiet detail',
            'furniture_density' => 'medium',
            'decorative_density' => 'medium_but_controlled',
            'material_temperature' => 'warm_muted',
            'lighting_bias' => 'soft_evening_lamp_and_window_balance',
            'scale_behavior' => 'collector_room_artwork_primary',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_pets', 'no_family_scene', 'no_decor_dominance', 'no_artwork_substitution'],
            'negative_context_terms' => ['busy living room', 'family gathering', 'pet', 'animal', 'crowd'],
        ],
        'midcentury_design_collector' => [
            'family_id' => 'midcentury_design_collector',
            'world_id' => 'period_design_world',
            'label' => 'Midcentury Design Collector',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['midcentury', 'design', 'collector', 'furniture_secondary'],
            'architecture_language' => 'clean design interior with midcentury proportions and collector discipline',
            'wall_language' => 'warm neutral wall, wood panel accent, or plaster backdrop',
            'floor_language' => 'wood, stone, or quiet rug with controlled pattern',
            'ceiling_language' => 'simple residential ceiling with period light allowed',
            'furniture_density' => 'medium',
            'decorative_density' => 'low_to_medium',
            'material_temperature' => 'warm_design',
            'lighting_bias' => 'warm_daylight_or_refined_lamp_light',
            'scale_behavior' => 'furniture_supports_artwork_never_competes',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['furniture_secondary', 'no_pets', 'no_catalog_room', 'no_artwork_substitution'],
            'negative_context_terms' => ['furniture ad', 'chair closeup', 'pet', 'animal', 'crowd'],
        ],
        'postmodern_design_room' => [
            'family_id' => 'postmodern_design_room',
            'world_id' => 'period_design_world',
            'label' => 'Postmodern Design Room',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['postmodern', 'design', 'collector', 'editorial', 'controlled_geometry', 'muted_color_blocking'],
            'architecture_language' => 'postmodern-informed interior with controlled geometry, muted color blocking, arches, niches, stepped planes, or graphic wall volumes kept subordinate to the artwork',
            'wall_language' => 'muted color-blocked wall, plaster, architectural paneling, niche, or geometric volume behind the artwork',
            'floor_language' => 'terrazzo, stone, patterned-but-quiet rug, or wood with low pattern load',
            'ceiling_language' => 'simple ceiling or one sculptural period light, always secondary',
            'furniture_density' => 'medium',
            'decorative_density' => 'medium_controlled',
            'material_temperature' => 'balanced_design',
            'lighting_bias' => 'controlled_editorial_light',
            'scale_behavior' => 'artwork_outweighs_design_objects_and_period_shapes',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_design_object_dominance', 'no_sculptural_lamp_dominance', 'no_graphic_wall_competing_with_artwork', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['product design ad', 'chair closeup', 'lamp as hero', 'graphic wall dominance', 'pet', 'animal', 'crowd'],
        ],
        'quiet_atelier_wall' => [
            'family_id' => 'quiet_atelier_wall',
            'world_id' => 'artist_studio_world',
            'label' => 'Quiet Atelier Wall',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['atelier', 'studio', 'wall', 'material'],
            'architecture_language' => 'working studio architecture, clean enough for premium presentation',
            'wall_language' => 'painted studio wall, plaster, pin marks allowed but subtle',
            'floor_language' => 'wood, concrete, or painted studio floor',
            'ceiling_language' => 'studio ceiling with soft practical light',
            'furniture_density' => 'low',
            'decorative_density' => 'low',
            'material_temperature' => 'neutral_to_warm_material',
            'lighting_bias' => 'north_light_or_soft_studio_daylight',
            'scale_behavior' => 'material_authenticity_with_artwork_primary',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['studio_objects_secondary', 'no_messy_clutter', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['messy workshop', 'paint chaos', 'pet', 'animal', 'crowd'],
        ],
        'collector_preview_studio_floor' => [
            'family_id' => 'collector_preview_studio_floor',
            'world_id' => 'artist_studio_world',
            'label' => 'Collector Preview Studio Floor',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['studio_floor', 'collector_preview', 'leaning_canvas'],
            'architecture_language' => 'refined studio or clean storage wall for previewing artwork',
            'wall_language' => 'plain wall, plaster, or storage wall',
            'floor_language' => 'visible studio floor, contact shadows important',
            'ceiling_language' => 'not dominant, simple studio ceiling',
            'furniture_density' => 'very_low',
            'decorative_density' => 'very_low',
            'material_temperature' => 'neutral_material',
            'lighting_bias' => 'soft_even_daylight',
            'scale_behavior' => 'floor_contact_and_canvas_depth_are_auditable',
            'presence_policy' => ['human' => 'none_or_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_pets', 'no_storage_clutter', 'no_canvas_warp', 'no_artwork_substitution'],
            'negative_context_terms' => ['warehouse clutter', 'pet', 'animal', 'crowd'],
        ],
        'quiet_collector_living_room' => [
            'family_id' => 'quiet_collector_living_room',
            'world_id' => 'domestic_collector_world',
            'label' => 'Quiet Collector Living Room',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['living_room', 'collector', 'domestic', 'warm'],
            'architecture_language' => 'cultivated private collector room with calm layout, cultural intimacy, and a silent artwork wall',
            'wall_language' => 'warm plaster, limewash, or muted painted wall',
            'floor_language' => 'wood, stone, or quiet rug',
            'ceiling_language' => 'domestic ceiling, understated fixtures',
            'furniture_density' => 'medium',
            'decorative_density' => 'medium_controlled',
            'material_temperature' => 'warm_domestic',
            'lighting_bias' => 'soft_window_light_or_evening_warmth',
            'scale_behavior' => 'private_collector_scale_with_artwork_as_cultural_center',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['artwork_must_remain_cultural_center', 'no_lifestyle_ad', 'no_real_estate_ad', 'no_pets', 'no_family_scene', 'no_decor_ad', 'no_artwork_substitution'],
            'negative_context_terms' => ['family lifestyle ad', 'real estate ad', 'decor ad', 'hotel catalog', 'pet', 'animal', 'crowd'],
        ],
        'private_study_collector_wall' => [
            'family_id' => 'private_study_collector_wall',
            'world_id' => 'domestic_collector_world',
            'label' => 'Private Study Collector Wall',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['study', 'collector', 'books', 'quiet'],
            'architecture_language' => 'private cultivated study with intellectual restraint and artwork as the cultural anchor',
            'wall_language' => 'deep paint, paneling, plaster, or books kept peripheral',
            'floor_language' => 'wood, rug, or stone in subdued palette',
            'ceiling_language' => 'residential ceiling, low visual emphasis',
            'furniture_density' => 'medium',
            'decorative_density' => 'medium_controlled',
            'material_temperature' => 'warm_deep',
            'lighting_bias' => 'soft_lamp_and_window_balance',
            'scale_behavior' => 'intimate_but_not_cropped_into_decor',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['artwork_must_remain_cultural_center', 'no_lifestyle_ad', 'no_real_estate_ad', 'no_pets', 'no_busy_bookshelf_dominance', 'no_artwork_substitution'],
            'negative_context_terms' => ['library clutter', 'real estate ad', 'lifestyle ad', 'pet', 'animal', 'crowd'],
        ],
        'quiet_luxury_living_space' => [
            'family_id' => 'quiet_luxury_living_space',
            'world_id' => 'premium_domestic_lifestyle_world',
            'label' => 'Quiet Luxury Living Space',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['quiet_luxury', 'controlled_lifestyle', 'premium', 'domestic', 'marketplace', 'room_scale'],
            'architecture_language' => 'aspirational domestic room such as living room, bedroom, dining room, suite, or elegant entry, with controlled commercial polish and negative space',
            'wall_language' => 'limewash, plaster, stone, or warm neutral painted wall',
            'floor_language' => 'stone, pale wood, or refined rug',
            'ceiling_language' => 'clean ceiling with premium indirect or natural light',
            'furniture_density' => 'medium',
            'decorative_density' => 'medium_but_subordinate',
            'material_temperature' => 'warm_premium',
            'lighting_bias' => 'polished_daylight_or_soft_golden_light',
            'scale_behavior' => 'room_scale_context_where_artwork_remains_reason_for_image',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['artwork_remains_reason_for_image', 'lifestyle_secondary', 'no_real_estate_ad', 'no_hotel_catalog_look', 'no_influencer_lifestyle', 'no_furniture_showroom', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['real estate ad', 'hotel catalog', 'influencer lifestyle', 'furniture showroom', 'decor ad', 'pet', 'animal', 'crowd'],
        ],
        'architect_designed_home_gallery' => [
            'family_id' => 'architect_designed_home_gallery',
            'world_id' => 'premium_domestic_lifestyle_world',
            'label' => 'Architect Designed Home Gallery',
            'status' => 'stable',
            'default_rotation' => true,
            'tags' => ['architect_home', 'aspirational_domestic', 'room_scale', 'premium', 'commercial'],
            'architecture_language' => 'architect-designed aspirational domestic gallery wall for an elegant entry, suite, dining room, living room, or home-gallery zone',
            'wall_language' => 'large uninterrupted wall plane with refined material',
            'floor_language' => 'stone, concrete, or wood with clear perspective lines',
            'ceiling_language' => 'architectural ceiling, skylight or slot light allowed',
            'furniture_density' => 'low_to_medium',
            'decorative_density' => 'low',
            'material_temperature' => 'balanced_premium',
            'lighting_bias' => 'architectural_daylight',
            'scale_behavior' => 'aspirational_room_scale_with_strong_artwork_priority',
            'presence_policy' => ['human' => 'optional_single_secondary', 'animal' => 'none'],
            'risk_controls' => ['artwork_remains_reason_for_image', 'no_real_estate_ad', 'no_real_estate_wide_shot', 'no_hotel_catalog_look', 'no_furniture_showroom', 'no_influencer_lifestyle', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['real estate wide angle', 'real estate ad', 'hotel catalog', 'furniture showroom', 'influencer lifestyle', 'pet', 'animal', 'crowd'],
        ],
        'monumental_concrete_hall' => [
            'family_id' => 'monumental_concrete_hall',
            'world_id' => 'experimental_monumental_world',
            'label' => 'Monumental Concrete Hall',
            'status' => 'experimental',
            'default_rotation' => false,
            'tags' => ['monumental', 'concrete', 'experimental', 'non_default'],
            'architecture_language' => 'physical monumental architecture: heroic concrete hall, atrium, or tall architectural volume, never an ordinary minimal gallery enlarged',
            'wall_language' => 'monumental concrete or mineral wall',
            'floor_language' => 'large concrete, stone, or polished floor plane',
            'ceiling_language' => 'high ceiling, beams, skylight, or large overhead structure',
            'furniture_density' => 'very_low',
            'decorative_density' => 'very_low',
            'material_temperature' => 'cool_mineral',
            'lighting_bias' => 'dramatic_architectural_daylight',
            'scale_behavior' => 'opt_in_monumental_scale_risk_control_required',
            'presence_policy' => ['human' => 'none_or_tiny_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_commercial_default', 'no_ordinary_minimal_gallery', 'no_simple_concrete_room_enlarged', 'no_dream_haze', 'no_fantasy_light', 'no_floating_objects', 'no_surreal_symbolic_scene', 'no_heroic_overscale', 'no_canvas_warp', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['ordinary minimal gallery', 'simple concrete room enlarged', 'dream haze', 'fantasy light', 'floating objects', 'surreal symbolic scene', 'billboard', 'mural scale', 'pet', 'animal', 'crowd'],
        ],
        'overscale_architectural_void' => [
            'family_id' => 'overscale_architectural_void',
            'world_id' => 'experimental_monumental_world',
            'label' => 'Overscale Architectural Void',
            'status' => 'experimental',
            'default_rotation' => false,
            'tags' => ['void', 'large_space', 'experimental', 'non_default'],
            'architecture_language' => 'physical monumental void with strong emptiness, distance, atrium-like volume, or high architectural risk, never a surreal dream space',
            'wall_language' => 'large quiet wall surface, not a billboard plane',
            'floor_language' => 'expansive floor plane with controlled perspective',
            'ceiling_language' => 'high or ambiguous ceiling, never theatrical',
            'furniture_density' => 'none',
            'decorative_density' => 'none_or_very_low',
            'material_temperature' => 'neutral_mineral',
            'lighting_bias' => 'soft_monumental_ambient_light',
            'scale_behavior' => 'physical_monumental_scale_guardrails_required',
            'presence_policy' => ['human' => 'none_or_tiny_secondary', 'animal' => 'none'],
            'risk_controls' => ['no_commercial_default', 'no_ordinary_minimal_gallery', 'no_dream_haze', 'no_fantasy_light', 'no_floating_objects', 'no_surreal_symbolic_scene', 'no_billboard_scaling', 'no_artwork_deformation', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['ordinary minimal gallery', 'simple concrete room enlarged', 'dream haze', 'fantasy light', 'floating objects', 'surreal symbolic scene', 'billboard', 'mural', 'pet', 'animal', 'crowd'],
        ],
        'poetic_threshold_room' => [
            'family_id' => 'poetic_threshold_room',
            'world_id' => 'poetic_surreal_world',
            'label' => 'Poetic Threshold Room',
            'status' => 'experimental',
            'default_rotation' => false,
            'tags' => ['poetic', 'threshold', 'experimental', 'non_default'],
            'architecture_language' => 'poetic threshold, doorway, curtain, or liminal room with quiet mystery, symbolic atmosphere, and no monumental scale',
            'wall_language' => 'muted atmospheric wall, plaster, shadow, or soft veil of light',
            'floor_language' => 'simple floor with restrained shadow geometry',
            'ceiling_language' => 'subtle or hidden ceiling plane',
            'furniture_density' => 'very_low',
            'decorative_density' => 'very_low',
            'material_temperature' => 'muted_atmospheric',
            'lighting_bias' => 'poetic_side_light_or_haze_without_obscuring_artwork',
            'scale_behavior' => 'poetic_liminal_mood_never_changes_artwork_or_scale',
            'presence_policy' => ['human' => 'none_or_silhouette_secondary', 'animal' => 'none'],
            'risk_controls' => ['mild_liminal_atmosphere_only', 'no_monumental_hall', 'no_oversized_architecture', 'no_heroic_museum_scale', 'no_brutalist_atrium', 'no_fantasy_illustration', 'no_symbolic_object_dominance', 'no_dream_scene_dominance', 'no_artwork_reinterpretation', 'no_pets', 'no_artwork_substitution'],
            'negative_context_terms' => ['monumental hall', 'oversized architecture', 'heroic museum scale', 'brutalist atrium', 'fantasy illustration', 'fantasy creature', 'symbolic object dominance', 'pet', 'animal', 'crowd', 'melting artwork'],
        ],
        'surreal_quiet_gallery' => [
            'family_id' => 'surreal_quiet_gallery',
            'world_id' => 'poetic_surreal_world',
            'label' => 'Surreal Quiet Gallery',
            'status' => 'experimental',
            'default_rotation' => false,
            'tags' => ['surreal', 'gallery', 'poetic', 'experimental'],
            'architecture_language' => 'quiet gallery with mild uncanny proportions or subtle light behavior only; no fantasy set, symbolic object dominance, or altered artwork',
            'wall_language' => 'plain wall with atmospheric gradient or shadow',
            'floor_language' => 'simple floor, reflections only if controlled',
            'ceiling_language' => 'minimal ceiling, no spectacle',
            'furniture_density' => 'none_or_very_low',
            'decorative_density' => 'none_or_very_low',
            'material_temperature' => 'cool_to_neutral_poetic',
            'lighting_bias' => 'subtle_uncanny_light_without_fantasy_effects',
            'scale_behavior' => 'mild_uncanny_only_artwork_identity_and_scale_locked',
            'presence_policy' => ['human' => 'none_or_silhouette_secondary', 'animal' => 'none'],
            'risk_controls' => ['mild_uncanny_only', 'no_fantasy', 'no_symbolic_object_dominance', 'no_altered_artwork', 'no_surreal_object_dominance', 'no_pets', 'no_artwork_reinterpretation', 'no_artwork_substitution'],
            'negative_context_terms' => ['fantasy illustration', 'fantasy scene', 'symbolic object dominance', 'altered artwork', 'pet', 'animal', 'crowd', 'melting artwork'],
        ],
        'quiet_pet_collector_room' => [
            'family_id' => 'quiet_pet_collector_room',
            'world_id' => 'pet_companion_world',
            'label' => 'Quiet Pet Collector Room',
            'status' => 'experimental',
            'default_rotation' => false,
            'tags' => ['pet', 'collector_room', 'animal_secondary', 'non_default'],
            'architecture_language' => 'quiet collector room with enough floor space to keep pet secondary',
            'wall_language' => 'calm wall where artwork remains clearly isolated and primary',
            'floor_language' => 'visible floor area for a resting pet away from the artwork',
            'ceiling_language' => 'simple domestic ceiling, not visually important',
            'furniture_density' => 'low_to_medium',
            'decorative_density' => 'low',
            'material_temperature' => 'warm_domestic',
            'lighting_bias' => 'soft_natural_light',
            'scale_behavior' => 'pet_must_not_change_artwork_scale_or_focus',
            'presence_policy' => ['human' => 'none', 'animal' => 'single_calm_pet_secondary_only'],
            'risk_controls' => ['single_calm_pet_only', 'pet_secondary_visual_weight', 'pet_must_not_block_artwork', 'no_pet_closeup', 'no_pet_portrait', 'no_pet_touching_canvas'],
            'negative_context_terms' => ['pet portrait', 'animal closeup', 'playing pet', 'pet on canvas', 'pet blocking artwork'],
        ],
        'pet_resting_studio_corner' => [
            'family_id' => 'pet_resting_studio_corner',
            'world_id' => 'pet_companion_world',
            'label' => 'Pet Resting Studio Corner',
            'status' => 'experimental',
            'default_rotation' => false,
            'tags' => ['pet', 'studio', 'resting', 'animal_secondary', 'non_default'],
            'architecture_language' => 'calm studio corner with artwork wall and unobtrusive resting pet zone',
            'wall_language' => 'plain studio wall, artwork has visual isolation',
            'floor_language' => 'studio floor with pet resting away from canvas contact',
            'ceiling_language' => 'simple studio ceiling or out of frame',
            'furniture_density' => 'very_low',
            'decorative_density' => 'very_low',
            'material_temperature' => 'neutral_warm',
            'lighting_bias' => 'soft_studio_daylight',
            'scale_behavior' => 'animal_secondary_and_low_visual_weight',
            'presence_policy' => ['human' => 'none', 'animal' => 'single_calm_pet_secondary_only'],
            'risk_controls' => ['single_calm_pet_only', 'pet_low_in_frame', 'pet_must_not_touch_canvas', 'no_pet_closeup', 'no_pet_portrait', 'no_playful_action'],
            'negative_context_terms' => ['pet portrait', 'animal closeup', 'playing pet', 'pet on canvas', 'pet blocking artwork'],
        ],
    ],
];
