<?php
declare(strict_types=1);

return [
    'default_slot_set_id' => 'phase_2_4_default_v1',
    'sets' => [
        'phase_2_4_default_v1' => [
            'set_name' => 'FASE 2.4 default camera slot set',
            'slots' => [
                'contrapicado_raton_puro',
                'contrapicado_7_8',
                'reflejo_dorado_tarde_palazzo',
                'vista_aerea_contexto_ventanas',
                'pasillo_obra_descentrada_proxima',
                'borgona_recovecos_3_4_loft_hormigon',
            ],
        ],
        'phase_2_6_experimental_v1' => [
            'set_name' => 'FASE 2.6 experimental camera composition set',
            'slots' => [
                'nadir_extremo_arquitectonico',
                'obra_apoyada_suelo_7_8',
                'diagonal_estudio_moderno',
                'luz_dorada_sombra_diagonal',
            ],
        ],
        'phase_2_6_artistic_detail_v1' => [
            'set_name' => 'FASE 2.6 artistic physical artwork detail set',
            'slots' => [
                'detalle_textura_lienzo',
                'borde_canvas_closeup',
                'esquina_obra_perspectiva_extrema',
                'rasante_superficie_pintura',
            ],
        ],
    ],
    'slots' => [
        'detalle_textura_lienzo' => [
            'slot_id' => 'detalle_textura_lienzo',
            'slot_name' => 'Detalle de Textura del Lienzo',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is very close to the artwork surface, using a close-up or semi-macro viewpoint focused on the physical painted skin of the canvas rather than the full room.',
            'lens_block' => 'Use a macro or close-focus lens equivalent with natural optical rendering, enough detail resolution to show pigment, texture, brushwork, relief, incisions, veladuras, or surface marks without making the artwork look digital.',
            'vertical_tilt_block' => 'Use only the vertical tilt needed to reveal surface relief and material texture. Full artwork readability is not required; selected texture areas must remain physically believable.',
            'lateral_rotation_block' => 'Use a close material angle across the painting surface, allowing partial cropping and shallow spatial depth while preserving the visible artwork identity.',
            'composition_block' => 'Partial cropping is allowed and expected. Close-up material framing and mild optical distortion from the close lens are allowed. The canvas or painted surface may fill most of the frame, showing only a fragment of the artwork. The purpose is materiality: pigment, brush marks, physical texture, relief, incisions, surface grain, and tactile presence.',
            'human_subject_block' => '',
            'scale_block' => 'Material scale protection: the visible surface remains a real physical artwork, not a poster, flat print, digital screen, or decorative texture. Artwork identity protection: preserve the real colors, visible marks, surface texture, and abstract visual identity of the provided artwork. Anti-substitution protection: do not invent new marks, figures, symbols, faces, landscapes, decorative motifs, or another painting.',
            'depth_of_field_block' => 'Shallow depth of field is allowed, but the selected artwork texture area must remain sharp and legible. Any blur must fall only outside the chosen focus plane and must feel optical and photographic.',
            'scene_affinity' => ['macro_texture', 'canvas_surface', 'material_detail', 'pigment', 'brushwork'],
            'negative_directives' => ['no poster', 'no flat print', 'no digital screen', 'no invented imagery', 'no artwork substitution', 'no plastic surface', 'no pets', 'no crowds', 'no children'],
        ],
        'borde_canvas_closeup' => [
            'slot_id' => 'borde_canvas_closeup',
            'slot_name' => 'Borde de Canvas Close-up',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is close to the wall-mounted canvas edge, positioned at artwork height or slightly oblique to read the front face, lateral side, thickness, and shadow against the nearby wall.',
            'lens_block' => 'Use a close-focus 50-70 mm lens equivalent or similar natural close-up lens that preserves plausible canvas thickness and avoids wide-angle exaggeration.',
            'vertical_tilt_block' => 'Keep vertical tilt controlled and material-oriented, enough to reveal edge depth and wall contact without making the canvas float or bend.',
            'lateral_rotation_block' => 'Use a close side-oblique angle across the canvas edge so the transition between painted front, lateral canvas depth, stretcher thickness, and wall shadow is visible.',
            'composition_block' => 'Partial artwork view is allowed and expected. This is a camera crop, not an artwork alteration. The full artwork does not need to be visible, and one or more artwork edges may fall outside the final image frame. Close-up optical distortion and mild foreshortening are allowed if they come from the physical lens and edge perspective. The canvas edge and thickness are the subject. The artwork may be cropped by the camera frame, with wall texture, lateral side, subtle cast shadow, and the physical transition from front surface to side edge carrying the composition. Preserve the original artwork format even when only a fragment is visible: a portrait artwork must still read as a fragment of a taller-than-wide canvas, a landscape artwork as a fragment of a wider-than-tall canvas, and a square artwork as square. Do not complete, widen, compress, or redesign the visible fragment into a different full-format painting.',
            'human_subject_block' => '',
            'scale_block' => 'Physical canvas protection: edge thickness must remain moderate and plausible for the real artwork depth; it must look like stretched canvas, not poster, paper, screen, floating panel, or exaggerated block. Artwork proportion protection: the physical canvas keeps the source artwork aspect ratio and orientation even if only a partial close-up is shown. Artwork identity protection: preserve exact artwork identity on the visible portion. Anti-substitution protection: do not replace the artwork with another image.',
            'depth_of_field_block' => 'Use close-up photographic depth of field. Canvas edge, visible artwork portion, side depth, and immediate wall contact should remain sharp; distant wall texture may soften gently.',
            'scene_affinity' => ['canvas_edge', 'wall_shadow', 'closeup', 'stretched_canvas', 'material_depth'],
            'negative_directives' => ['no poster', 'no flat print', 'no digital screen', 'no floating panel', 'no exaggerated thickness', 'no artwork substitution', 'no pets', 'no crowds', 'no children'],
        ],
        'esquina_obra_perspectiva_extrema' => [
            'slot_id' => 'esquina_obra_perspectiva_extrema',
            'slot_name' => 'Corte Agresivo de Esquina de Obra',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is placed extremely close to one physical canvas corner or edge, almost touching the artwork plane, so the image cuts aggressively across the artwork rather than showing a normal room mockup.',
            'lens_block' => 'Use a close optical lens equivalent with shallow depth and strong foreshortening. The lens may crop the artwork hard and skim across the surface, but must not melt, bend, tear, curve, or reshape the canvas geometry.',
            'vertical_tilt_block' => 'Use only the tilt needed to cut across the artwork corner and reveal thickness, surface texture, subtle sheen, humidity-like highlights, and edge depth. The canvas remains a rigid physical rectangle under optical perspective.',
            'lateral_rotation_block' => 'Use an aggressive side-oblique angle across one real artwork corner, around 10-25 degrees along the artwork plane, so the frame cuts the artwork and may exclude large portions of it. The camera should read as a close artistic slice over the painting surface, not a distant side view of a room.',
            'composition_block' => 'Partial cropping is required. The full artwork should usually not be visible. Let the image cut through one angle or corner of the artwork, with the canvas edge, front surface, thickness, texture, slight moisture-like sheen, and gentle gloss carrying the composition. Preserve the local composition exactly in the visible area: existing lines, color blocks, marks, boundaries, symbols, and proportions must remain from the reference artwork. Do not invent landscapes, figures, new symbols, new brush marks, or a different pictorial composition.',
            'human_subject_block' => '',
            'scale_block' => 'Physical canvas protection: the canvas may look dramatic through optical perspective, but it must not melt, bend, curve, tear, warp, taper into an impossible wedge, or lose rigid rectangular credibility. Artwork identity protection: preserve visible colors, marks, texture, abstract identity, and local composition from the provided artwork. Anti-substitution protection: do not replace it with figurative, classical, historical, portrait, landscape, decorative, or invented painting. Do not repaint the visible fragment, do not change the composition inside the cropped area, and do not turn surface sheen into new imagery.',
            'depth_of_field_block' => 'Shallow depth of field is allowed. The selected physical corner, nearby edge, surface texture, subtle gloss, humidity-like highlights, and visible artwork marks must remain sharp enough to read as the real artwork; only distant cropped surface areas may fall softly out of focus.',
            'scene_affinity' => ['canvas_corner', 'aggressive_crop', 'extreme_perspective', 'foreshortening', 'material_edge', 'surface_sheen', 'artistic_detail'],
            'negative_directives' => ['no full-room side view', 'no distant mockup view', 'no melted canvas', 'no bent canvas', 'no torn canvas', 'no impossible wedge', 'no changed composition', 'no invented marks', 'no invented landscape', 'no digital screen', 'no artwork substitution', 'no invented painting', 'no pets', 'no crowds', 'no children'],
        ],
        'rasante_superficie_pintura' => [
            'slot_id' => 'rasante_superficie_pintura',
            'slot_name' => 'Rasante de Superficie Pictórica',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is extremely close and almost parallel to the painting surface, like a grazing shot across the skin of the artwork plane.',
            'lens_block' => 'Use a close-focus macro or material-detail lens equivalent with natural shallow optical depth, emphasizing pigment, texture, brushwork, incisions, scratches, relief, and physical surface presence.',
            'vertical_tilt_block' => 'Use a very low grazing angle along the painting surface. The full artwork does not need to be visible; the focus must fall on a real visible area of the artwork surface.',
            'lateral_rotation_block' => 'Run the viewpoint laterally along the painting plane so texture and relief create depth, with partial cropping expected and no need for full rectangular readability.',
            'composition_block' => 'Partial cropping is expected. The image is a rasante view over the artwork surface, emphasizing material skin, pigment depth, relief, shine, texture transitions, and tactile presence rather than room context.',
            'human_subject_block' => '',
            'scale_block' => 'Material protection: the surface must remain a real painted canvas or artwork material, not plastic, glossy digital, poster-like, printed paper, or screen-like. Artwork identity protection: preserve the provided artwork color world, visible marks, and material identity. Anti-substitution protection: do not invent new imagery or replace the painting.',
            'depth_of_field_block' => 'Shallow depth of field is allowed and expected. The selected focus ridge, mark, pigment area, or texture band must be sharp; foreground and background surface areas may soften naturally along the grazing plane.',
            'scene_affinity' => ['grazing_surface', 'macro_material', 'pigment_relief', 'brushwork', 'surface_skin'],
            'negative_directives' => ['no plastic surface', 'no glossy digital look', 'no digital screen', 'no poster-like print', 'no printed-paper appearance', 'no invented imagery', 'no artwork substitution', 'no pets', 'no crowds', 'no children'],
        ],
        'nadir_extremo_arquitectonico' => [
            'slot_id' => 'nadir_extremo_arquitectonico',
            'slot_name' => 'Nadir Extremo Arquitectónico',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is positioned at true floor level, approximately 1-3 cm from the floor, almost touching the ground, as if the lens is lying on the floor at the corner of the room. The camera is not centered in front of the artwork; it sits near one lateral wall or floor/wall junction and looks sharply upward across the artwork zone. The floor must dominate the lower foreground and feel physically close to the lens, while walls, columns, beams, slabs, doors, luminaires, wall joints, or vertical architectural planes tower upward through the composition.',
            'lens_block' => 'Use an extreme architectural wide lens equivalent, about 14-20 mm. Strong perspective exaggeration, stretched floor foreground, rising verticals, diagonal convergence, and dramatic optical depth are allowed and desired. Avoid cartoon circular fisheye rings, but do not sanitize the perspective into a normal 24-35 mm gallery view.',
            'vertical_tilt_block' => 'Use an unmistakable steep upward nadir or contrapicado tilt, almost vertical from the floor toward the wall, ceiling, beams, slabs, skylights, and vertical structure. The camera must look up from below and beside the artwork zone, not from a centered frontal axis. The artwork may be visibly foreshortened by perspective, but it must remain recognizable as the same rigid physical artwork.',
            'lateral_rotation_block' => 'Use an extreme low diagonal rotation from a floor corner or side-wall position, with a strong upward vanishing direction shared by the artwork, wall, floor, ceiling, furniture, and architectural verticals. The room should feel pulled into a steep diagonal vortex. Avoid any centered, symmetrical, straight-on product wall view.',
            'composition_block' => 'Build the drama through a radical bottom-up diagonal architectural view. Do not center the artwork as a frontal monument. The lower floor edge or near floor plane should occupy a large part of the lower frame, with one side wall or floor/wall seam rushing past the camera and architecture rising overhead. Extreme nadir views work best in spaces with mass, height, and clear architectural structure: brutalist architecture, exposed concrete galleries, tall vertical walls, architectural atriums, industrial minimalist lofts, high ceiling collector spaces, concrete beams, slabs, columns, skylights, or vertical openings. The drama comes from extreme off-axis camera position, stretched floor foreground, rising verticals, diagonal convergence, and exaggerated spatial depth. Floor lines, vertical wall planes, ceiling height, columns, door frames, beams, luminaires, furniture legs, wall joints, and overhead structural planes must visibly carry the nadir effect. The artwork remains identifiable and visually important, but the camera can make the surrounding room perspective feel almost deformed.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains a physically plausible canvas in the room. Canvas perspective protection: the canvas is a rigid rectangular physical object under aggressive lens perspective; controlled foreshortening is allowed, but do not melt, tear, curve, liquid-warp, or replace the artwork identity. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not replace it with figurative, classical, historical, portrait, landscape, decorative, or old-master-style painting.',
            'depth_of_field_block' => 'Keep the artwork, canvas edges, canvas thickness, and artwork texture sharp and legible. Only very close floor foreground or distant ceiling and architectural planes may soften slightly; the blur must remain subtle, optical, and photographic.',
            'scene_affinity' => ['floor_plane', 'nadir', 'architectural_verticals', 'columns', 'ceiling_height', 'brutalist_architecture', 'exposed_concrete_gallery', 'architectural_atrium', 'industrial_minimalist_loft', 'high_ceiling_collector_space'],
            'best_fit' => ['brutalist architecture', 'exposed concrete gallery', 'tall vertical wall', 'architectural atrium', 'industrial minimalist loft', 'high ceiling collector space', 'strong vertical structure', 'monumental but restrained architecture', 'concrete beams', 'slabs', 'columns', 'skylights', 'vertical openings'],
            'curatorial_rule' => 'Extreme nadir views work best in spaces with mass, height, and clear architectural structure. Brutalist or monumental architecture is especially suitable because the drama comes from the rising architecture, not from enlarging or deforming the artwork.',
            'avoid_scene_affinity' => ['low domestic rooms', 'cozy living rooms', 'soft decorative interiors', 'cramped rooms', 'flat walls with no architectural height', 'scenes where drama would require warping the canvas or oversizing the artwork'],
            'negative_directives' => ['no centered frontal composition', 'no symmetrical monument view', 'no straight-on product wall view', 'no eye-level view', 'no standing-height view', 'no normal 3/4 gallery photo', 'no gentle low angle', 'no soft controlled viewpoint', 'no flat wall view', 'no melted artwork', 'no torn canvas', 'no artwork substitution', 'no artwork reinterpretation', 'no classical painting substitution', 'no low domestic rooms', 'no cozy living rooms', 'no cramped rooms', 'no pets', 'no crowds', 'no children'],
        ],
        'obra_apoyada_suelo_7_8' => [
            'slot_id' => 'obra_apoyada_suelo_7_8',
            'slot_name' => 'Obra Apoyada en Suelo 7/8',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is low or medium-low, approximately 35-90 cm from the floor, close enough to read the physical bottom edge, floor contact, floor plane, wall plane, and leaning relationship.',
            'lens_block' => 'Use a disciplined 45-60 mm lens equivalent that preserves believable scale, canvas depth, and wall/floor geometry without wide-angle stretching or heroic enlargement.',
            'vertical_tilt_block' => 'Use a modest vertical tilt only as needed to keep the leaning artwork readable; avoid forcing the front face into an impossible skew, billboard scale, or theatrical monumental angle.',
            'lateral_rotation_block' => 'Use a restrained 3/4 or 7/8 side-oblique view so the side edge, canvas depth, exact floor contact, and slight backward lean against the wall are visible through one coherent perspective.',
            'composition_block' => 'The artwork is not hanging. It must lean with physically believable gravity either against a real vertical wall or against a real stable object that could plausibly support a canvas in an atelier or collector preview, such as a low cabinet, sturdy table edge, studio rack, crate, storage block, easel-like support, or large furniture side. The support must be coherent with the room, not an invented monumental display plinth. The bottom edge should rest on the real floor or on a clearly stable low surface with visible contact shadows and believable load-bearing contact. Use a slight backward lean of about 5-12 degrees only. The scene may read as atelier, collector preview, clean storage wall, or refined studio. Off-center framing is allowed so floor, support object, wall, and side depth communicate the physical object, but the artwork must stay physically grounded and naturally placed.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork keeps physically plausible real scale according to the artwork technical data supplied in the final prompt, leaning on the floor or against a stable support. It is a substantial studio artwork, not a monumental wall panel, billboard, room divider, stage prop, or oversized slab. The artwork height should read lower than a normal adult person unless the supplied artwork dimensions explicitly indicate otherwise, and it should remain well below a typical door height when the artwork dimensions support that reading. Canvas perspective protection: keep the front face rectangular and optically faithful, side thickness moderate, bottom edge grounded, and floor/support contact believable. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not replace it with figurative, classical, historical, portrait, landscape, decorative, or old-master-style painting.',
            'depth_of_field_block' => 'Keep the artwork face, canvas edges, bottom edge, contact point, and texture sharp. Subtle depth falloff may soften distant studio objects or far wall planes, but never the artwork or its physical support contact.',
            'scene_affinity' => ['atelier', 'collector_preview', 'storage_wall', 'studio_floor', 'leaning_canvas'],
            'negative_directives' => ['no hanging artwork', 'no wall-mounted artwork', 'no impossible support', 'no invented monumental plinth', 'no floating canvas', 'no unsupported canvas', 'no unstable balancing', 'no arbitrary placement', 'no oversized canvas', 'no billboard scaling', 'no poster', 'no flat print', 'no canvas wedge', 'no artwork substitution', 'no pets', 'no crowds', 'no children'],
        ],
        'diagonal_estudio_moderno' => [
            'slot_id' => 'diagonal_estudio_moderno',
            'slot_name' => 'Diagonal Moderna de Estudio',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is medium or moderately low, approximately 70-140 cm, with an editorial studio viewpoint that lets architectural diagonals guide the eye.',
            'lens_block' => 'Use a clean 35-50 mm editorial architectural lens equivalent, avoiding exaggerated width while preserving clear room depth.',
            'vertical_tilt_block' => 'Keep vertical tilt controlled and mostly natural so diagonal composition comes from architecture, light, and framing rather than distortion.',
            'lateral_rotation_block' => 'Use a diagonal three-quarter composition where floor lines, ceiling lines, railings, benches, linear lights, wall seams, shadows, or side walls lead toward the artwork.',
            'composition_block' => 'Strong diagonal leading lines direct the viewer toward the artwork as the visual destination. Off-center placement is allowed and encouraged when it strengthens the diagonal flow. The photograph should feel contemporary, editorial, and spatial rather than centered and product-like.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains physically plausible and optically faithful while the surrounding studio geometry creates movement. Canvas perspective protection: keep the canvas rigid, rectangular, crisp, and aligned to the same vanishing logic as floor, wall, ceiling, furniture, and architectural lines. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not repaint, replace, or reinterpret it.',
            'depth_of_field_block' => 'Keep artwork, canvas edges, and artwork texture sharp. Secondary foreground diagonals or distant studio planes may soften slightly if it supports photographic depth, but the artwork remains the focus plane.',
            'scene_affinity' => ['modern_studio', 'diagonal_lines', 'editorial', 'architectural_edges', 'linear_lighting'],
            'negative_directives' => ['no centered product symmetry', 'no artwork deformation', 'no artwork substitution', 'no poster effect', 'no pets', 'no crowds', 'no children'],
        ],
        'luz_dorada_sombra_diagonal' => [
            'slot_id' => 'luz_dorada_sombra_diagonal',
            'slot_name' => 'Luz Dorada y Sombra Diagonal',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is natural gallery or collector viewing height, approximately 120-170 cm, calm enough to let golden window light and diagonal shadow geometry structure the image.',
            'lens_block' => 'Use a refined 40-55 mm lens equivalent with natural compression, preserving artwork scale, wall plane, and light/shadow transitions without distortion.',
            'vertical_tilt_block' => 'Use minimal vertical tilt. Keep the artwork plane calm, legible, and physically credible while light and shadow provide the compositional energy.',
            'lateral_rotation_block' => 'Use a soft frontal-oblique or moderate 3/4 camera angle, enough to show wall depth and room atmosphere without competing with the diagonal light composition.',
            'composition_block' => 'Build the composition from golden late-afternoon window light and a strong diagonal shadow across wall or floor. Place the artwork near the transition between light and shadow. The room may feel like a palazzo, atelier, townhouse, warm gallery, or Mediterranean interior. Avoid overexposing the artwork; the artwork remains sharp, faithful, and visually readable.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains a physically plausible wall-mounted canvas near the light/shadow transition. Canvas perspective protection: keep the canvas rectangular, rigid, and aligned with wall and floor perspective; do not warp, deform, bend, taper, or turn it into a wedge. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not recolor it with golden light, repaint it, replace it, or reinterpret it.',
            'depth_of_field_block' => 'Use little to moderate natural depth of field. The artwork surface, canvas edges, texture, and light/shadow boundary near the artwork remain crisp; only distant room planes may soften gently.',
            'scene_affinity' => ['golden_light', 'diagonal_shadow', 'palazzo', 'atelier', 'townhouse', 'mediterranean'],
            'negative_directives' => ['no overexposed artwork', 'no recolored artwork', 'no artwork substitution', 'no poster effect', 'no pets', 'no crowds', 'no children'],
        ],
        'contrapicado_raton_puro' => [
            'slot_id' => 'contrapicado_raton_puro',
            'slot_name' => 'Nadir Controlado',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is positioned extremely low, approximately 5-15 cm from the ground, with the lens nearly touching the floor. This is a mouse-level/nadir-inspired architectural viewpoint, not a gentle low 3/4. The floor plane must be large and close in the foreground while wall height, ceiling lines, columns, door frames or architectural verticals rise strongly.',
            'lens_block' => 'Use an aggressive wide architectural lens equivalent, about 20-26 mm. Strong perspective expansion, stretched near floor foreground, and dramatic vanishing lines are allowed and desired, while avoiding cartoon circular fisheye.',
            'vertical_tilt_block' => 'Use a strong upward nadir-inspired tilt toward the wall and surrounding architecture. The camera must visibly look up from near floor level. The artwork may be seen from below with clear foreshortening, yet it must remain recognizable as a rigid physical canvas.',
            'lateral_rotation_block' => 'Use an assertive oblique angle across the room, not a straight-on product view, with one forceful vanishing direction for architecture and artwork. The wall, floor, ceiling, and artwork should feel pulled into the same steep perspective.',
            'composition_block' => 'Use the nadir effect strongly through the surrounding room geometry: a large foreground floor wedge, floor lines, vertical wall planes, ceiling height, architectural edges, columns, furniture legs or door frames. The artwork remains the visual subject, but the dramatic low viewpoint must be obvious at thumbnail size. Do not produce a polite standing-height gallery view.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork is a rigid rectangular physical canvas under aggressive lens perspective. Controlled foreshortening and strong side-depth exaggeration are allowed; do not melt, tear, curve, liquid-warp, or replace the artwork identity. Preserve the exact abstract artwork from the reference image. Canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Keep the artwork, canvas edges and artwork texture sharp. A slight softness may appear only in very close floor foreground or distant ceiling/architectural planes. Do not blur the artwork.',
            'scene_affinity' => ['floor_plane', 'studio', 'gallery', 'architectural_wall'],
            'negative_directives' => ['no eye-level view', 'no standing-height view', 'no normal 3/4 gallery photo', 'no gentle low angle', 'no soft controlled viewpoint', 'no flat wall view', 'no melted artwork', 'no torn canvas', 'no artwork substitution', 'no fashion-model posing', 'no pets', 'no crowds', 'no children'],
        ],
        'contrapicado_7_8' => [
            'slot_id' => 'contrapicado_7_8',
            'slot_name' => 'Contrapicado 7/8',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is aggressively low, 5-20 cm from the floor, clearly far below knee height. The viewpoint must feel like the lens is near the floor and close to the wall, not standing height, not chest height, and not a normal eye-level gallery view.',
            'lens_block' => 'Use an aggressive wide architectural lens equivalent, about 20-28 mm. Strong side-depth exaggeration, stretched near foreground, and intense perspective convergence are allowed and desired. Avoid cartoon circular fisheye, but do not normalize the view into a polite 35-50 mm product photo.',
            'vertical_tilt_block' => 'Use a strong visible upward low-angle tilt from below the artwork centerline. The viewer should read the underside/lower edge relationship of the canvas, with wall verticals, ceiling lines, track lights, or architecture rising sharply upward. If the result could be mistaken for a normal eye-level 3/4 wall view, the camera is wrong.',
            'lateral_rotation_block' => 'Use a very strong 7/8 oblique rotation so the wall, artwork side depth, floor plane, and room volume rush toward one shared vanishing direction. The side of the canvas can feel dramatically deep through perspective, while the artwork remains a rigid object.',
            'composition_block' => 'The artwork is seen with aggressive side depth and believable thickness from a near-floor 7/8 viewpoint. Include a large visible floor wedge or floor plane in the lower foreground, with wall/floor junctions and architectural verticals proving the camera is below knee height. Use strong asymmetry, a close foreground edge, and negative space toward the vanishing side while keeping surrounding wall and floor aligned to the same camera. This must feel almost perspective-deformed and must not collapse into a standard standing-height 3/4 gallery photograph.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork may occupy a strong visual position, but its apparent size must remain consistent with the physical XL canvas. Canvas integrity: the canvas is a rigid physical rectangle under aggressive perspective; strong foreshortening and exaggerated side-depth are allowed, but the front face must not melt, tear, curve, liquid-warp, or become a different artwork. Canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use controlled photographic depth of field to separate foreground, artwork, and vanishing-side architecture: the artwork face, canvas edges, and visible texture remain completely sharp; only secondary foreground or distant background planes may soften subtly.',
            'scene_affinity' => ['loft', 'gallery', 'statement_wall', 'architectural_depth'],
            'negative_directives' => ['no eye-level view', 'no standing-height view', 'no normal 3/4 gallery photo', 'no gentle low angle', 'no soft controlled viewpoint', 'no flat wall view', 'no melted artwork', 'no torn canvas', 'no artwork substitution', 'no random people', 'no pets', 'no crowds', 'no children'],
        ],
        'reflejo_dorado_tarde_palazzo' => [
            'slot_id' => 'reflejo_dorado_tarde_palazzo',
            'slot_name' => 'Reflejo Dorado de Tarde / Palazzo',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is elegant human standing height, approximately 150-170 cm, as if observed calmly from inside a palazzo room.',
            'lens_block' => 'Use a refined 40-50 mm lens equivalent with natural compression and no exaggerated room depth.',
            'vertical_tilt_block' => 'Keep vertical tilt minimal and steady, preserving dignified wall geometry and a calm institutional reading.',
            'lateral_rotation_block' => 'Use a soft three-quarter rotation that catches reflected late light while keeping the artwork plane legible.',
            'composition_block' => 'The composition is stable, warm, and architectural, with golden afternoon reflection supporting the room rather than repainting the artwork; keep elegant balance but avoid perfect symmetry unless the room itself naturally demands it.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork is a plausible XL wall-mounted object in a refined interior, neither miniaturized nor monumentally enlarged. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use minimal depth of field. The room, artwork, canvas edges, and artwork texture should remain mostly crisp; any softness is barely perceptible and limited to distant secondary planes.',
            'scene_affinity' => ['palazzo', 'collector_room', 'warm_reflection', 'late_afternoon'],
            'negative_directives' => ['no artwork color redescription', 'no fashion-model posing', 'no animals', 'no crowds', 'no children', 'no pets'],
        ],
        'vista_aerea_contexto_ventanas' => [
            'slot_id' => 'vista_aerea_contexto_ventanas',
            'slot_name' => 'Nadir Aéreo con Contexto de Ventanas',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is positioned very high, near ceiling height, upper balcony height, skylight height, or the top edge of a tall architectural void. It is the aerial counterpart of an extreme nadir: instead of looking upward from the floor, the camera looks downward from above into the room.',
            'lens_block' => 'Use a controlled 28-40 mm architectural lens equivalent, wide enough to read the room from above but restrained enough to avoid fisheye, drone, surveillance, or real-estate plan-view behavior.',
            'vertical_tilt_block' => 'Use a steep downward aerial-nadir tilt. The floor is the receiving plane of the image, and wall planes, windows, furniture, and the artwork wall drop downward through one coherent high-angle perspective.',
            'lateral_rotation_block' => 'Use an oblique high-corner or upper-balcony diagonal, not a centered frontal wall view. The camera may look diagonally down along the room so window context, floor geometry, and artwork wall are visible together.',
            'composition_block' => 'Build the image from above: visible floor plane, furniture or bench tops, rug or floor layout, wall height, window/skylight context, and the artwork installed on a vertical wall. The artwork remains identifiable, but the room must read as seen from above, not as a normal wall presentation.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork occupies a plausible portion of the wall in an aerial-nadir composition with strong visible floor plane and surrounding architecture. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, windows, furniture, and architecture share one coherent downward high-angle vanishing logic.',
            'depth_of_field_block' => 'Use little to no depth of field because the elevated architectural view needs readable spatial geometry. Keep the artwork, canvas edges, floor lines, windows, and main room planes crisp.',
            'scene_affinity' => ['windows', 'aerial_nadir', 'high_angle', 'visible_floor_plane', 'upper_balcony', 'skylight', 'architectural_context'],
            'negative_directives' => ['no eye-level wall view', 'no standing-height view', 'no centered frontal presentation', 'no simple elevated 3/4', 'no drone distance', 'no surveillance view', 'no decorative random people', 'no pets', 'no crowds', 'no children'],
        ],
        'pasillo_obra_descentrada_proxima' => [
            'slot_id' => 'pasillo_obra_descentrada_proxima',
            'slot_name' => 'Pasillo, Obra Descentrada y Próxima',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is natural standing or slightly lowered human height, close enough to feel the corridor edge.',
            'lens_block' => 'Use a 35-45 mm lens equivalent suited to corridor depth, with controlled perspective and no stretched hallway exaggeration.',
            'vertical_tilt_block' => 'Keep vertical tilt nearly level, allowing corridor lines and the artwork plane to stay believable.',
            'lateral_rotation_block' => 'Use an offset three-quarter corridor angle, with the artwork deliberately off-center and close rather than symmetrically framed.',
            'composition_block' => 'Place the artwork on a long wall plane rather than a short frontal display wall. The wall should extend laterally into the scene like a gallery passage, corridor, or elongated architectural plane, creating a clear vanishing direction. Use floor lines, ceiling lines, wall joints, lighting tracks, windows, columns, doorways, or distant wall planes to reinforce depth. The artwork may sit off-center and relatively close to the viewer, while the architecture recedes naturally to one side. Avoid product-style centered symmetry.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork reads as a substantial XL piece in a corridor offset composition, not as a wall-filling billboard. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Set the focus plane firmly on the artwork. Keep the artwork surface, canvas edges, canvas thickness, artwork texture, and the wall area immediately around the artwork sharp and fully legible. Use a visible natural depth-of-field falloff with a subtle diorama-like effect only away from the artwork plane. The distant corridor, far wall planes, remote columns, background windows, far doorways, ceiling depth, floor depth, and the corridor end should fall noticeably but naturally out of focus. Foreground architectural edges may be slightly soft if they are closer to the camera than the artwork. The blur must feel optical and photographic, not artificial. Never blur the artwork, its canvas edges, its texture, or the immediate wall around it.',
            'scene_affinity' => ['corridor', 'offset_composition', 'near_wall', 'architectural_edge'],
            'negative_directives' => ['no billboard scaling', 'no fashion-model posing', 'no animals', 'no crowds', 'no children', 'no pets'],
        ],
        'borgona_recovecos_3_4_loft_hormigon' => [
            'slot_id' => 'borgona_recovecos_3_4_loft_hormigon',
            'slot_name' => 'Borgoña Recovecos / Cámara 3/4 en Loft de Hormigón',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is human but tucked into an architectural recess, approximately 120-160 cm depending on the loft edge.',
            'lens_block' => 'Use a 35-50 mm lens equivalent with tactile concrete depth and no aggressive wide-angle distortion.',
            'vertical_tilt_block' => 'Keep tilt controlled and mostly level so concrete planes, wall geometry, and artwork edges remain coherent.',
            'lateral_rotation_block' => 'Use a 3/4 view from a recess, corner, or architectural edge, with a burgundy-toned spatial mood and one clean vanishing direction.',
            'composition_block' => 'The artwork is partially contextualized by loft recesses and concrete architecture, creating depth and intimacy without hiding the piece; allow strong off-center framing through recesses, corners, side planes, or architectural edges.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains a physically plausible XL canvas within the concrete loft, balanced by recess depth rather than global dominance. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use controlled shallow spatial depth: recess edges, side planes, or distant loft surfaces may soften subtly, while the artwork face, canvas edges, and artwork texture remain fully sharp and legible.',
            'scene_affinity' => ['loft', 'concrete', 'recess', 'three_quarter', 'burgundy_mood'],
            'negative_directives' => ['no artwork deformation', 'no random decorative people', 'no animals', 'no crowds', 'no children', 'no pets'],
        ],
    ],
];
