<?php
declare(strict_types=1);

return [
    'schema' => 'mockup_context_worlds.v1',
    'normal_rotation_rule' => 'Only status=stable and default_rotation=true may be used for future normal generation.',
    'worlds' => [
        'minimal_contemporary_world' => [
            'world_id' => 'minimal_contemporary_world',
            'label' => 'Minimal Contemporary World',
            'description' => 'Commercially usable contemporary gallery, loft, home-gallery, and sober concrete contexts with restrained architecture, low visual noise, and artwork-first presentation. Not a monumental atrium, heroic-scale architecture, or architectural spectacle.',
            'status' => 'stable',
            'default_rotation' => true,
            'usage_type' => 'commercial_default',
            'tags' => ['minimal', 'contemporary', 'gallery', 'collector', 'commercial', 'art_first'],
            'allowed_presence' => ['human' => 'none_or_single_secondary_scale_reference', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_optional_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'commercially_usable_scale', 'no_monumental_atrium', 'no_heroic_scale', 'no_architectural_spectacle', 'no_pets', 'no_crowds', 'no_decorative_clutter', 'no_artwork_substitution'],
            'families' => ['minimal_white_gallery', 'contemporary_concrete_collector'],
        ],
        'historical_european_world' => [
            'world_id' => 'historical_european_world',
            'label' => 'Historical European World',
            'description' => 'European palazzo, townhouse, and period architectural interiors where old materials frame contemporary artwork without overpowering it.',
            'status' => 'stable',
            'default_rotation' => true,
            'usage_type' => 'commercial_default',
            'tags' => ['historical', 'european', 'palazzo', 'townhouse', 'collector', 'premium'],
            'allowed_presence' => ['human' => 'none_or_single_secondary_scale_reference', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_optional_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'no_pets', 'no_period_costume_scene', 'no_museum_crowds', 'no_artwork_substitution'],
            'families' => ['european_palazzo_gallery', 'old_townhouse_collector_room'],
        ],
        'period_design_world' => [
            'world_id' => 'period_design_world',
            'label' => 'Period Design World',
            'description' => 'Design-led interiors with mid-century, postmodern, or collectible furniture language kept secondary to the artwork.',
            'status' => 'stable',
            'default_rotation' => true,
            'usage_type' => 'commercial_default',
            'tags' => ['period_design', 'collectible_design', 'interior_design', 'premium', 'art_first'],
            'allowed_presence' => ['human' => 'none_or_single_secondary_scale_reference', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_optional_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'furniture_secondary', 'no_catalog_furniture_dominance', 'no_pets', 'no_artwork_substitution'],
            'families' => ['midcentury_design_collector', 'postmodern_design_room'],
        ],
        'artist_studio_world' => [
            'world_id' => 'artist_studio_world',
            'label' => 'Artist Studio World',
            'description' => 'Refined atelier and studio contexts with physical process, storage, floor contact, and material authenticity.',
            'status' => 'stable',
            'default_rotation' => true,
            'usage_type' => 'commercial_default',
            'tags' => ['artist_studio', 'atelier', 'material', 'process', 'collector_preview'],
            'allowed_presence' => ['human' => 'none_or_single_secondary_artist_or_collector', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_optional_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'studio_objects_secondary', 'no_messy_clutter', 'no_pets', 'no_artwork_substitution'],
            'families' => ['quiet_atelier_wall', 'collector_preview_studio_floor'],
        ],
        'domestic_collector_world' => [
            'world_id' => 'domestic_collector_world',
            'label' => 'Domestic Collector World',
            'description' => 'Cultivated private collector homes: intimate, silent, culturally literate domestic rooms where the artwork is the cultural center of the home, not lifestyle decoration.',
            'status' => 'stable',
            'default_rotation' => true,
            'usage_type' => 'commercial_default',
            'tags' => ['private_home', 'cultivated_collector', 'intimate', 'silent', 'cultural_center', 'art_first'],
            'allowed_presence' => ['human' => 'none_or_single_secondary_scale_reference', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_optional_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_cultural_center', 'no_lifestyle_ad', 'no_real_estate_ad', 'no_pets', 'no_family_scene', 'no_decor_ad', 'no_artwork_substitution'],
            'families' => ['quiet_collector_living_room', 'private_study_collector_wall'],
        ],
        'premium_domestic_lifestyle_world' => [
            'world_id' => 'premium_domestic_lifestyle_world',
            'label' => 'Premium Domestic Lifestyle World',
            'description' => 'Controlled aspirational/commercial domestic spaces for bedroom, dining room, living room, suite, or elegant entry contexts where the artwork elevates the room without becoming a decor advertisement.',
            'status' => 'stable',
            'default_rotation' => true,
            'usage_type' => 'commercial_default',
            'tags' => ['premium_lifestyle', 'domestic', 'marketplace', 'aspirational_domestic', 'controlled_lifestyle', 'room_scale'],
            'allowed_presence' => ['human' => 'none_or_single_secondary_scale_reference', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_optional_secondary_only',
            'default_risk_controls' => ['artwork_remains_reason_for_image', 'lifestyle_secondary', 'no_real_estate_ad', 'no_hotel_catalog_look', 'no_influencer_lifestyle', 'no_furniture_showroom', 'no_pets', 'no_artwork_substitution'],
            'families' => ['quiet_luxury_living_space', 'architect_designed_home_gallery'],
        ],
        'experimental_monumental_world' => [
            'world_id' => 'experimental_monumental_world',
            'label' => 'Experimental Monumental World',
            'description' => 'Opt-in monumental physical architecture: heroic halls, atriums, voids, and scale-risk spaces for controlled non-default testing. Not an ordinary minimal gallery, not commercial default, and not a simple concrete room enlarged.',
            'status' => 'experimental',
            'default_rotation' => false,
            'usage_type' => 'experimental_opt_in',
            'tags' => ['experimental', 'monumental', 'architecture', 'non_default', 'scale_risk'],
            'allowed_presence' => ['human' => 'none_or_tiny_secondary_scale_reference', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_rare_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'no_commercial_default', 'no_ordinary_minimal_gallery', 'no_simple_concrete_room_enlarged', 'no_dream_haze', 'no_fantasy_light', 'no_floating_objects', 'no_surreal_symbolic_scene', 'no_heroic_overscale', 'no_canvas_deformation', 'no_pets', 'no_artwork_substitution'],
            'families' => ['monumental_concrete_hall', 'overscale_architectural_void'],
        ],
        'poetic_surreal_world' => [
            'world_id' => 'poetic_surreal_world',
            'label' => 'Poetic Surreal World',
            'description' => 'Opt-in poetic, liminal, symbolic, and mildly surreal atmospheres for editorial experimentation while protecting artwork identity. Not monumental architecture, not heroic museum scale, and not fantasy illustration.',
            'status' => 'experimental',
            'default_rotation' => false,
            'usage_type' => 'experimental_opt_in',
            'tags' => ['poetic', 'surreal', 'experimental', 'non_default', 'editorial'],
            'allowed_presence' => ['human' => 'none_or_silhouette_secondary', 'animal' => 'none'],
            'default_presence_policy' => 'no_animals_humans_silhouette_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'no_monumental_hall', 'no_oversized_architecture', 'no_heroic_museum_scale', 'no_brutalist_atrium', 'no_fantasy_illustration', 'no_dream_scene_dominance', 'no_artwork_reinterpretation', 'no_pets', 'no_artwork_substitution'],
            'families' => ['poetic_threshold_room', 'surreal_quiet_gallery'],
        ],
        'pet_companion_world' => [
            'world_id' => 'pet_companion_world',
            'label' => 'Pet Companion World',
            'description' => 'Opt-in companion animal world where one calm pet may appear only as a quiet secondary presence while the artwork remains protagonist.',
            'status' => 'experimental',
            'default_rotation' => false,
            'usage_type' => 'experimental_opt_in',
            'tags' => ['pet', 'companion', 'animal_presence', 'experimental', 'non_default', 'controlled_presence'],
            'allowed_presence' => ['human' => 'none', 'animal' => 'single_calm_pet_secondary_only'],
            'default_presence_policy' => 'single_calm_pet_secondary_only',
            'default_risk_controls' => ['artwork_must_remain_primary', 'single_calm_pet_only', 'pet_secondary_visual_weight', 'pet_must_not_block_artwork', 'no_pet_closeup', 'no_pet_portrait', 'no_pet_touching_canvas', 'no_playful_action'],
            'families' => ['quiet_pet_collector_room', 'pet_resting_studio_corner'],
        ],
    ],
];
