<?php
declare(strict_types=1);

return [
    'default_slot_set_id' => 'phase_2_4_default_v1',
    'sets' => [
        'phase_2_4_default_v1' => [
            'set_name' => 'FASE 2.4 default camera slot set',
            'slots' => [
                'contrapicado_raton_puro',
                'contrapicado_7_8',
                'reflejo_dorado_tarde_palazzo',
                'vista_aerea_contexto_ventanas',
                'pasillo_obra_descentrada_proxima',
                'borgona_recovecos_3_4_loft_hormigon',
            ],
        ],
        'phase_2_6_experimental_v1' => [
            'set_name' => 'FASE 2.6 experimental camera composition set',
            'slots' => [
                'nadir_extremo_arquitectonico',
                'obra_apoyada_suelo_7_8',
                'diagonal_estudio_moderno',
                'luz_dorada_sombra_diagonal',
            ],
        ],
        'phase_2_6_artistic_detail_v1' => [
            'set_name' => 'FASE 2.6 artistic physical artwork detail set',
            'slots' => [
                'detalle_textura_lienzo',
                'borde_canvas_closeup',
                'esquina_obra_perspectiva_extrema',
                'rasante_superficie_pintura',
            ],
        ],
    ],
    'slots' => [
        'detalle_textura_lienzo' => [
            'slot_id' => 'detalle_textura_lienzo',
            'slot_name' => 'Detalle de Textura del Lienzo',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is very close to the artwork surface, using a close-up or semi-macro viewpoint focused on the physical painted skin of the canvas rather than the full room.',
            'lens_block' => 'Use a macro or close-focus lens equivalent with natural optical rendering, enough detail resolution to show pigment, texture, brushwork, relief, incisions, veladuras, or surface marks without making the artwork look digital.',
            'vertical_tilt_block' => 'Use only the vertical tilt needed to reveal surface relief and material texture. Full artwork readability is not required; selected texture areas must remain physically believable.',
            'lateral_rotation_block' => 'Use a close material angle across the painting surface, allowing partial cropping and shallow spatial depth while preserving the visible artwork identity.',
            'composition_block' => 'Partial cropping is allowed and expected. Close-up material framing and mild optical distortion from the close lens are allowed. The canvas or painted surface may fill most of the frame, showing only a fragment of the artwork. The purpose is materiality: pigment, brush marks, physical texture, relief, incisions, surface grain, and tactile presence.',
            'human_subject_block' => '',
            'scale_block' => 'Material scale protection: the visible surface remains a real physical artwork, not a poster, flat print, digital screen, or decorative texture. Artwork identity protection: preserve the real colors, visible marks, surface texture, and abstract visual identity of the provided artwork. Anti-substitution protection: do not invent new marks, figures, symbols, faces, landscapes, decorative motifs, or another painting.',
            'depth_of_field_block' => 'Shallow depth of field is allowed, but the selected artwork texture area must remain sharp and legible. Any blur must fall only outside the chosen focus plane and must feel optical and photographic.',
            'scene_affinity' => ['macro_texture', 'canvas_surface', 'material_detail', 'pigment', 'brushwork'],
            'negative_directives' => ['no poster', 'no flat print', 'no digital screen', 'no invented imagery', 'no artwork substitution', 'no plastic surface', 'no pets', 'no crowds', 'no children'],
        ],
        'borde_canvas_closeup' => [
            'slot_id' => 'borde_canvas_closeup',
            'slot_name' => 'Borde de Canvas Close-up',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is close to the wall-mounted canvas edge, positioned at artwork height or slightly oblique to read the front face, lateral side, thickness, and shadow against the nearby wall.',
            'lens_block' => 'Use a close-focus 50-70 mm lens equivalent or similar natural close-up lens that preserves plausible canvas thickness and avoids wide-angle exaggeration.',
            'vertical_tilt_block' => 'Keep vertical tilt controlled and material-oriented, enough to reveal edge depth and wall contact without making the canvas float or bend.',
            'lateral_rotation_block' => 'Use a close side-oblique angle across the canvas edge so the transition between painted front, lateral canvas depth, stretcher thickness, and wall shadow is visible.',
            'composition_block' => 'Partial artwork view is allowed. Close-up optical distortion and mild foreshortening are allowed if they come from the physical lens and edge perspective. The canvas edge and thickness are the subject. The artwork may be cropped, with wall texture, lateral side, subtle cast shadow, and the physical transition from front surface to side edge carrying the composition.',
            'human_subject_block' => '',
            'scale_block' => 'Physical canvas protection: edge thickness must remain moderate and plausible for the real artwork depth; it must look like stretched canvas, not poster, paper, screen, floating panel, or exaggerated block. Artwork identity protection: preserve exact artwork identity on the visible portion. Anti-substitution protection: do not replace the artwork with another image.',
            'depth_of_field_block' => 'Use close-up photographic depth of field. Canvas edge, visible artwork portion, side depth, and immediate wall contact should remain sharp; distant wall texture may soften gently.',
            'scene_affinity' => ['canvas_edge', 'wall_shadow', 'closeup', 'stretched_canvas', 'material_depth'],
            'negative_directives' => ['no poster', 'no flat print', 'no digital screen', 'no floating panel', 'no exaggerated thickness', 'no artwork substitution', 'no pets', 'no crowds', 'no children'],
        ],
        'esquina_obra_perspectiva_extrema' => [
            'slot_id' => 'esquina_obra_perspectiva_extrema',
            'slot_name' => 'Corte Agresivo de Esquina de Obra',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is placed extremely close to one physical canvas corner or edge, almost touching the artwork plane, so the image cuts aggressively across the artwork rather than showing a normal room mockup.',
            'lens_block' => 'Use a close optical lens equivalent with shallow depth and strong foreshortening. The lens may crop the artwork hard and skim across the surface, but must not melt, bend, tear, curve, or reshape the canvas geometry.',
            'vertical_tilt_block' => 'Use only the tilt needed to cut across the artwork corner and reveal thickness, surface texture, subtle sheen, humidity-like highlights, and edge depth. The canvas remains a rigid physical rectangle under optical perspective.',
            'lateral_rotation_block' => 'Use an aggressive side-oblique angle across one real artwork corner, around 10-25 degrees along the artwork plane, so the frame cuts the artwork and may exclude large portions of it. The camera should read as a close artistic slice over the painting surface, not a distant side view of a room.',
            'composition_block' => 'Partial cropping is required. The full artwork should usually not be visible. Let the image cut through one angle or corner of the artwork, with the canvas edge, front surface, thickness, texture, slight moisture-like sheen, and gentle gloss carrying the composition. Preserve the local composition exactly in the visible area: existing lines, color blocks, marks, boundaries, symbols, and proportions must remain from the reference artwork. Do not invent landscapes, figures, new symbols, new brush marks, or a different pictorial composition.',
            'human_subject_block' => '',
            'scale_block' => 'Physical canvas protection: the canvas may look dramatic through optical perspective, but it must not melt, bend, curve, tear, warp, taper into an impossible wedge, or lose rigid rectangular credibility. Artwork identity protection: preserve visible colors, marks, texture, abstract identity, and local composition from the provided artwork. Anti-substitution protection: do not replace it with figurative, classical, historical, portrait, landscape, decorative, or invented painting. Do not repaint the visible fragment, do not change the composition inside the cropped area, and do not turn surface sheen into new imagery.',
            'depth_of_field_block' => 'Shallow depth of field is allowed. The selected physical corner, nearby edge, surface texture, subtle gloss, humidity-like highlights, and visible artwork marks must remain sharp enough to read as the real artwork; only distant cropped surface areas may fall softly out of focus.',
            'scene_affinity' => ['canvas_corner', 'aggressive_crop', 'extreme_perspective', 'foreshortening', 'material_edge', 'surface_sheen', 'artistic_detail'],
            'negative_directives' => ['no full-room side view', 'no distant mockup view', 'no melted canvas', 'no bent canvas', 'no torn canvas', 'no impossible wedge', 'no changed composition', 'no invented marks', 'no invented landscape', 'no digital screen', 'no artwork substitution', 'no invented painting', 'no pets', 'no crowds', 'no children'],
        ],
        'rasante_superficie_pintura' => [
            'slot_id' => 'rasante_superficie_pintura',
            'slot_name' => 'Rasante de Superficie Pictórica',
            'enabled' => true,
            'fidelity_mode' => 'artistic_optical_distortion',
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is extremely close and almost parallel to the painting surface, like a grazing shot across the skin of the artwork plane.',
            'lens_block' => 'Use a close-focus macro or material-detail lens equivalent with natural shallow optical depth, emphasizing pigment, texture, brushwork, incisions, scratches, relief, and physical surface presence.',
            'vertical_tilt_block' => 'Use a very low grazing angle along the painting surface. The full artwork does not need to be visible; the focus must fall on a real visible area of the artwork surface.',
            'lateral_rotation_block' => 'Run the viewpoint laterally along the painting plane so texture and relief create depth, with partial cropping expected and no need for full rectangular readability.',
            'composition_block' => 'Partial cropping is expected. The image is a rasante view over the artwork surface, emphasizing material skin, pigment depth, relief, shine, texture transitions, and tactile presence rather than room context.',
            'human_subject_block' => '',
            'scale_block' => 'Material protection: the surface must remain a real painted canvas or artwork material, not plastic, glossy digital, poster-like, printed paper, or screen-like. Artwork identity protection: preserve the provided artwork color world, visible marks, and material identity. Anti-substitution protection: do not invent new imagery or replace the painting.',
            'depth_of_field_block' => 'Shallow depth of field is allowed and expected. The selected focus ridge, mark, pigment area, or texture band must be sharp; foreground and background surface areas may soften naturally along the grazing plane.',
            'scene_affinity' => ['grazing_surface', 'macro_material', 'pigment_relief', 'brushwork', 'surface_skin'],
            'negative_directives' => ['no plastic surface', 'no glossy digital look', 'no digital screen', 'no poster-like print', 'no printed-paper appearance', 'no invented imagery', 'no artwork substitution', 'no pets', 'no crowds', 'no children'],
        ],
        'nadir_extremo_arquitectonico' => [
            'slot_id' => 'nadir_extremo_arquitectonico',
            'slot_name' => 'Nadir Extremo Arquitectónico',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is positioned at true floor level, approximately 2-8 cm from the floor, almost touching the ground and looking sharply upward from below the artwork zone. The floor must be felt as the starting plane of the image, while walls, columns, beams, slabs, doors, luminaires, wall joints, or vertical architectural planes tower upward through the composition.',
            'lens_block' => 'Use a controlled architectural wide-normal lens equivalent, about 28-35 mm, wide enough to feel the low viewpoint but restrained enough to avoid fisheye, stretched edges, or impossible room geometry.',
            'vertical_tilt_block' => 'Use an unmistakable steep upward nadir or contrapicado tilt, not a high-angle view and not a normal frontal wall view. The camera looks from near the floor toward the wall, ceiling, beams, slabs, skylights, and vertical structure. The artwork may be seen from below, but the tilt must not force extreme distortion of the artwork plane.',
            'lateral_rotation_block' => 'Use a disciplined low oblique architectural rotation with one coherent upward vanishing direction shared by the artwork, wall, floor, ceiling, furniture, and architectural verticals. Avoid flattening into a straight-on product wall view.',
            'composition_block' => 'Build the drama through a true bottom-up architectural view, not through warping the artwork. The lower floor edge or near floor plane should anchor the frame, and the architecture should rise overhead. Extreme nadir views work best in spaces with mass, height, and clear architectural structure: brutalist architecture, exposed concrete galleries, tall vertical walls, architectural atriums, industrial minimalist lofts, high ceiling collector spaces, concrete beams, slabs, columns, skylights, or vertical openings. The drama comes from rising monumental but restrained architecture, not from enlarging or deforming the artwork. Floor lines, vertical wall planes, ceiling height, columns, door frames, beams, luminaires, furniture legs, wall joints, and overhead structural planes carry the nadir effect. The artwork remains identifiable and visually important without being centered like a product shot.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains a physically plausible canvas in the room. Canvas perspective protection: the canvas is a rigid rectangular physical object; do not bend, warp, taper, stretch, curve, turn it into a wedge, exaggerate side thickness, deform texture, or break the artwork identity. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not replace it with figurative, classical, historical, portrait, landscape, decorative, or old-master-style painting.',
            'depth_of_field_block' => 'Keep the artwork, canvas edges, canvas thickness, and artwork texture sharp and legible. Only very close floor foreground or distant ceiling and architectural planes may soften slightly; the blur must remain subtle, optical, and photographic.',
            'scene_affinity' => ['floor_plane', 'nadir', 'architectural_verticals', 'columns', 'ceiling_height', 'brutalist_architecture', 'exposed_concrete_gallery', 'architectural_atrium', 'industrial_minimalist_loft', 'high_ceiling_collector_space'],
            'best_fit' => ['brutalist architecture', 'exposed concrete gallery', 'tall vertical wall', 'architectural atrium', 'industrial minimalist loft', 'high ceiling collector space', 'strong vertical structure', 'monumental but restrained architecture', 'concrete beams', 'slabs', 'columns', 'skylights', 'vertical openings'],
            'curatorial_rule' => 'Extreme nadir views work best in spaces with mass, height, and clear architectural structure. Brutalist or monumental architecture is especially suitable because the drama comes from the rising architecture, not from enlarging or deforming the artwork.',
            'avoid_scene_affinity' => ['low domestic rooms', 'cozy living rooms', 'soft decorative interiors', 'cramped rooms', 'flat walls with no architectural height', 'scenes where drama would require warping the canvas or oversizing the artwork'],
            'negative_directives' => ['no fisheye', 'no canvas wedge', 'no artwork deformation', 'no heroic oversized artwork', 'no artwork substitution', 'no artwork reinterpretation', 'no classical painting substitution', 'no low domestic rooms', 'no cozy living rooms', 'no cramped rooms', 'no pets', 'no crowds', 'no children'],
        ],
        'obra_apoyada_suelo_7_8' => [
            'slot_id' => 'obra_apoyada_suelo_7_8',
            'slot_name' => 'Obra Apoyada en Suelo 7/8',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is low or medium-low, approximately 35-90 cm from the floor, close enough to read the physical bottom edge, floor contact, and leaning relationship.',
            'lens_block' => 'Use a disciplined 35-45 mm lens equivalent that preserves believable scale, canvas depth, and wall/floor geometry without wide-angle stretching.',
            'vertical_tilt_block' => 'Use a modest vertical tilt only as needed to keep the leaning artwork readable; avoid forcing the front face into an impossible skew.',
            'lateral_rotation_block' => 'Use a 3/4 or 7/8 side-oblique view so the side edge, canvas depth, floor contact, and backward lean against the wall are visible through one coherent perspective.',
            'composition_block' => 'The artwork is not hanging. It leans against the wall with its bottom edge resting on the floor and a slight backward lean. The scene may read as atelier, collector preview, clean storage wall, or refined studio. Off-center framing is allowed so floor, wall, and side depth communicate the physical object.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork keeps physically plausible XL scale as a rigid canvas leaning against a wall. Canvas perspective protection: keep the front face rectangular and optically faithful, side thickness moderate, bottom edge grounded, and wall/floor contact believable. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not replace it with figurative, classical, historical, portrait, landscape, decorative, or old-master-style painting.',
            'depth_of_field_block' => 'Keep the artwork face, canvas edges, bottom edge, and texture sharp. Subtle depth falloff may soften distant studio objects or far wall planes, but never the artwork or its floor contact.',
            'scene_affinity' => ['atelier', 'collector_preview', 'storage_wall', 'studio_floor', 'leaning_canvas'],
            'negative_directives' => ['no hanging artwork', 'no poster', 'no flat print', 'no canvas wedge', 'no artwork substitution', 'no pets', 'no crowds', 'no children'],
        ],
        'diagonal_estudio_moderno' => [
            'slot_id' => 'diagonal_estudio_moderno',
            'slot_name' => 'Diagonal Moderna de Estudio',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is medium or moderately low, approximately 70-140 cm, with an editorial studio viewpoint that lets architectural diagonals guide the eye.',
            'lens_block' => 'Use a clean 35-50 mm editorial architectural lens equivalent, avoiding exaggerated width while preserving clear room depth.',
            'vertical_tilt_block' => 'Keep vertical tilt controlled and mostly natural so diagonal composition comes from architecture, light, and framing rather than distortion.',
            'lateral_rotation_block' => 'Use a diagonal three-quarter composition where floor lines, ceiling lines, railings, benches, linear lights, wall seams, shadows, or side walls lead toward the artwork.',
            'composition_block' => 'Strong diagonal leading lines direct the viewer toward the artwork as the visual destination. Off-center placement is allowed and encouraged when it strengthens the diagonal flow. The photograph should feel contemporary, editorial, and spatial rather than centered and product-like.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains physically plausible and optically faithful while the surrounding studio geometry creates movement. Canvas perspective protection: keep the canvas rigid, rectangular, crisp, and aligned to the same vanishing logic as floor, wall, ceiling, furniture, and architectural lines. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not repaint, replace, or reinterpret it.',
            'depth_of_field_block' => 'Keep artwork, canvas edges, and artwork texture sharp. Secondary foreground diagonals or distant studio planes may soften slightly if it supports photographic depth, but the artwork remains the focus plane.',
            'scene_affinity' => ['modern_studio', 'diagonal_lines', 'editorial', 'architectural_edges', 'linear_lighting'],
            'negative_directives' => ['no centered product symmetry', 'no artwork deformation', 'no artwork substitution', 'no poster effect', 'no pets', 'no crowds', 'no children'],
        ],
        'luz_dorada_sombra_diagonal' => [
            'slot_id' => 'luz_dorada_sombra_diagonal',
            'slot_name' => 'Luz Dorada y Sombra Diagonal',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is natural gallery or collector viewing height, approximately 120-170 cm, calm enough to let golden window light and diagonal shadow geometry structure the image.',
            'lens_block' => 'Use a refined 40-55 mm lens equivalent with natural compression, preserving artwork scale, wall plane, and light/shadow transitions without distortion.',
            'vertical_tilt_block' => 'Use minimal vertical tilt. Keep the artwork plane calm, legible, and physically credible while light and shadow provide the compositional energy.',
            'lateral_rotation_block' => 'Use a soft frontal-oblique or moderate 3/4 camera angle, enough to show wall depth and room atmosphere without competing with the diagonal light composition.',
            'composition_block' => 'Build the composition from golden late-afternoon window light and a strong diagonal shadow across wall or floor. Place the artwork near the transition between light and shadow. The room may feel like a palazzo, atelier, townhouse, warm gallery, or Mediterranean interior. Avoid overexposing the artwork; the artwork remains sharp, faithful, and visually readable.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains a physically plausible wall-mounted canvas near the light/shadow transition. Canvas perspective protection: keep the canvas rectangular, rigid, and aligned with wall and floor perspective; do not warp, deform, bend, taper, or turn it into a wedge. Artwork fidelity protection: preserve the exact abstract artwork from the reference image; do not recolor it with golden light, repaint it, replace it, or reinterpret it.',
            'depth_of_field_block' => 'Use little to moderate natural depth of field. The artwork surface, canvas edges, texture, and light/shadow boundary near the artwork remain crisp; only distant room planes may soften gently.',
            'scene_affinity' => ['golden_light', 'diagonal_shadow', 'palazzo', 'atelier', 'townhouse', 'mediterranean'],
            'negative_directives' => ['no overexposed artwork', 'no recolored artwork', 'no artwork substitution', 'no poster effect', 'no pets', 'no crowds', 'no children'],
        ],
        'contrapicado_raton_puro' => [
            'slot_id' => 'contrapicado_raton_puro',
            'slot_name' => 'Nadir Controlado',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera is positioned very low, near the floor, approximately 20-35 cm from the ground, using a controlled nadir-inspired architectural viewpoint. The floor plane, wall height, ceiling lines, columns, door frames or architectural verticals may rise strongly in the composition.',
            'lens_block' => 'Use a natural architectural wide-normal lens equivalent, about 28-35 mm, with no fisheye behavior and no stretched edges.',
            'vertical_tilt_block' => 'Use an upward nadir-inspired tilt toward the wall and surrounding architecture, but do not force an extreme distortion of the artwork plane. The artwork may be seen from slightly below, yet its front face must remain readable, rectangular, optically faithful and physically credible.',
            'lateral_rotation_block' => 'Use a controlled oblique angle across the room, not a straight-on product view, with one coherent vanishing direction for architecture and artwork.',
            'composition_block' => 'Use the nadir effect mainly through the surrounding room geometry: floor lines, vertical wall planes, ceiling height, architectural edges, columns, furniture legs or door frames. The artwork remains the visual subject, but the dramatic low viewpoint is carried by the architecture rather than by warping the canvas.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork is a rigid rectangular physical canvas. Do not bend, warp, taper, stretch, curve, turn into a wedge, or exaggerate side thickness. Preserve the exact abstract artwork from the reference image. Do not replace it with figurative, classical, historical, portrait, landscape, decorative or old-master-style painting. Canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Keep the artwork, canvas edges and artwork texture sharp. A slight softness may appear only in very close floor foreground or distant ceiling/architectural planes. Do not blur the artwork.',
            'scene_affinity' => ['floor_plane', 'studio', 'gallery', 'architectural_wall'],
            'negative_directives' => ['no fisheye', 'no artwork deformation', 'no fashion-model posing', 'no pets', 'no crowds', 'no children'],
        ],
        'contrapicado_7_8' => [
            'slot_id' => 'contrapicado_7_8',
            'slot_name' => 'Contrapicado 7/8',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is low, below normal knee height, with the viewpoint grounded close to the floor but still architectural.',
            'lens_block' => 'Use a disciplined 30-40 mm architectural lens equivalent, wide enough for room depth but restrained enough to protect geometry.',
            'vertical_tilt_block' => 'Use an upward low-angle tilt that feels intentional and controlled, not extreme or theatrical.',
            'lateral_rotation_block' => 'Use a 7/8 oblique rotation so the wall, artwork depth, and room volume are visible through one shared perspective.',
            'composition_block' => 'The artwork is seen with strong side depth and believable thickness; use clear asymmetry and negative space toward the vanishing side while keeping surrounding wall and floor aligned to the same camera.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork may occupy a strong visual position, but its apparent size must remain consistent with the physical XL canvas. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use controlled photographic depth of field to separate foreground, artwork, and vanishing-side architecture: the artwork face, canvas edges, and visible texture remain completely sharp; only secondary foreground or distant background planes may soften subtly.',
            'scene_affinity' => ['loft', 'gallery', 'statement_wall', 'architectural_depth'],
            'negative_directives' => ['no fisheye', 'no scale distortion', 'no random people', 'no pets', 'no crowds', 'no children'],
        ],
        'reflejo_dorado_tarde_palazzo' => [
            'slot_id' => 'reflejo_dorado_tarde_palazzo',
            'slot_name' => 'Reflejo Dorado de Tarde / Palazzo',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is elegant human standing height, approximately 150-170 cm, as if observed calmly from inside a palazzo room.',
            'lens_block' => 'Use a refined 40-50 mm lens equivalent with natural compression and no exaggerated room depth.',
            'vertical_tilt_block' => 'Keep vertical tilt minimal and steady, preserving dignified wall geometry and a calm institutional reading.',
            'lateral_rotation_block' => 'Use a soft three-quarter rotation that catches reflected late light while keeping the artwork plane legible.',
            'composition_block' => 'The composition is stable, warm, and architectural, with golden afternoon reflection supporting the room rather than repainting the artwork; keep elegant balance but avoid perfect symmetry unless the room itself naturally demands it.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork is a plausible XL wall-mounted object in a refined interior, neither miniaturized nor monumentally enlarged. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use minimal depth of field. The room, artwork, canvas edges, and artwork texture should remain mostly crisp; any softness is barely perceptible and limited to distant secondary planes.',
            'scene_affinity' => ['palazzo', 'collector_room', 'warm_reflection', 'late_afternoon'],
            'negative_directives' => ['no artwork color redescription', 'no fashion-model posing', 'no animals', 'no crowds', 'no children', 'no pets'],
        ],
        'vista_aerea_contexto_ventanas' => [
            'slot_id' => 'vista_aerea_contexto_ventanas',
            'slot_name' => 'Vista Aérea con Contexto de Ventanas',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is elevated above normal eye level, high enough to read the room, windows, floor plane, and artwork together.',
            'lens_block' => 'Use a controlled 35-45 mm architectural lens equivalent; the view is elevated and spatial, not a distant drone image.',
            'vertical_tilt_block' => 'Use a calm downward high-angle tilt that relates windows, floor, furniture, wall, and artwork through one camera.',
            'lateral_rotation_block' => 'Use a gentle diagonal rotation so window context and the artwork wall are both visible without splitting perspectives.',
            'composition_block' => 'The room is comprehensible from above, with window light and floor geometry giving context while the artwork remains identifiable; allow a moderate offset so floor, windows, and surrounding architecture carry part of the frame.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork occupies a plausible portion of the wall in an aerial composition with visible floor plane and surrounding architecture. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use little to no depth of field because the elevated architectural view needs readable spatial geometry. Keep the artwork, canvas edges, floor lines, windows, and main room planes crisp.',
            'scene_affinity' => ['windows', 'high_angle', 'visible_floor_plane', 'architectural_context'],
            'negative_directives' => ['no drone distance', 'no surveillance view', 'no decorative random people', 'no pets', 'no crowds', 'no children'],
        ],
        'pasillo_obra_descentrada_proxima' => [
            'slot_id' => 'pasillo_obra_descentrada_proxima',
            'slot_name' => 'Pasillo, Obra Descentrada y Próxima',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is natural standing or slightly lowered human height, close enough to feel the corridor edge.',
            'lens_block' => 'Use a 35-45 mm lens equivalent suited to corridor depth, with controlled perspective and no stretched hallway exaggeration.',
            'vertical_tilt_block' => 'Keep vertical tilt nearly level, allowing corridor lines and the artwork plane to stay believable.',
            'lateral_rotation_block' => 'Use an offset three-quarter corridor angle, with the artwork deliberately off-center and close rather than symmetrically framed.',
            'composition_block' => 'Place the artwork on a long wall plane rather than a short frontal display wall. The wall should extend laterally into the scene like a gallery passage, corridor, or elongated architectural plane, creating a clear vanishing direction. Use floor lines, ceiling lines, wall joints, lighting tracks, windows, columns, doorways, or distant wall planes to reinforce depth. The artwork may sit off-center and relatively close to the viewer, while the architecture recedes naturally to one side. Avoid product-style centered symmetry.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork reads as a substantial XL piece in a corridor offset composition, not as a wall-filling billboard. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Set the focus plane firmly on the artwork. Keep the artwork surface, canvas edges, canvas thickness, artwork texture, and the wall area immediately around the artwork sharp and fully legible. Use a visible natural depth-of-field falloff with a subtle diorama-like effect only away from the artwork plane. The distant corridor, far wall planes, remote columns, background windows, far doorways, ceiling depth, floor depth, and the corridor end should fall noticeably but naturally out of focus. Foreground architectural edges may be slightly soft if they are closer to the camera than the artwork. The blur must feel optical and photographic, not artificial. Never blur the artwork, its canvas edges, its texture, or the immediate wall around it.',
            'scene_affinity' => ['corridor', 'offset_composition', 'near_wall', 'architectural_edge'],
            'negative_directives' => ['no billboard scaling', 'no fashion-model posing', 'no animals', 'no crowds', 'no children', 'no pets'],
        ],
        'borgona_recovecos_3_4_loft_hormigon' => [
            'slot_id' => 'borgona_recovecos_3_4_loft_hormigon',
            'slot_name' => 'Borgoña Recovecos / Cámara 3/4 en Loft de Hormigón',
            'enabled' => true,
            'size_classes_supported' => ['xl'],
            'orientation_supported' => ['horizontal', 'landscape', 'vertical', 'portrait', 'square', 'unknown'],
            'camera_height_block' => 'Camera height is human but tucked into an architectural recess, approximately 120-160 cm depending on the loft edge.',
            'lens_block' => 'Use a 35-50 mm lens equivalent with tactile concrete depth and no aggressive wide-angle distortion.',
            'vertical_tilt_block' => 'Keep tilt controlled and mostly level so concrete planes, wall geometry, and artwork edges remain coherent.',
            'lateral_rotation_block' => 'Use a 3/4 view from a recess, corner, or architectural edge, with a burgundy-toned spatial mood and one clean vanishing direction.',
            'composition_block' => 'The artwork is partially contextualized by loft recesses and concrete architecture, creating depth and intimacy without hiding the piece; allow strong off-center framing through recesses, corners, side planes, or architectural edges.',
            'human_subject_block' => '',
            'scale_block' => 'The artwork remains a physically plausible XL canvas within the concrete loft, balanced by recess depth rather than global dominance. Canvas integrity: the canvas is a rigid physical rectangle; the front face must not bend, curve, stretch, or become a wedge, lateral thickness stays moderate and plausible, and canvas plane, wall plane, floor lines, furniture, and architecture share one coherent vanishing logic.',
            'depth_of_field_block' => 'Use controlled shallow spatial depth: recess edges, side planes, or distant loft surfaces may soften subtly, while the artwork face, canvas edges, and artwork texture remain fully sharp and legible.',
            'scene_affinity' => ['loft', 'concrete', 'recess', 'three_quarter', 'burgundy_mood'],
            'negative_directives' => ['no artwork deformation', 'no random decorative people', 'no animals', 'no crowds', 'no children', 'no pets'],
        ],
    ],
];
