<?php
declare(strict_types=1); require_once dirname(__DIR__) . '/app/bootstrap.php';
PublicPage::start('Privacy Policy | Artwork Mockups','Learn how Artwork Mockups collects, uses and protects account, artwork and third-party integration data.','privacy/');
?>
<span class="eyebrow">Legal · Effective July 13, 2026</span><h1>Privacy Policy</h1>
<p class="lede">This policy explains how Artwork Mockups, available at artworkmockups.com, handles information when artists create accounts, upload artwork, generate mockups, and use optional third-party integrations.</p>
<nav class="toc" aria-label="Contents"><strong>Contents</strong><ol><li><a href="#data">Data we collect</a></li><li><a href="#use">How we use data</a></li><li><a href="#providers">Providers and AI</a></li><li><a href="#pinterest">Pinterest</a></li><li><a href="#meta">Meta</a></li><li><a href="#retention">Retention</a></li><li><a href="#security">Security</a></li><li><a href="#rights">Your rights</a></li><li><a href="#cookies">Cookies</a></li></ol></nav>
<section id="data"><h2>1. Data we collect</h2><p>We may collect registration and account information such as name, email address, authentication records and account settings. We process original artworks, uploaded images, dimensions, generated mockups, titles, descriptions and related project information that you choose to provide.</p><p>We also collect limited technical information needed to operate and secure the service, including device and browser data, IP address, timestamps, request and activity records, error information and security events.</p></section>
<section id="use"><h2>2. How we use information</h2><p>We use information to provide accounts, process images, generate and store mockups, display project history, provide support, protect the platform, investigate abuse, meet legal obligations and improve reliability. We do not claim ownership of your original artwork.</p></section>
<section id="providers"><h2>3. Infrastructure, AI and third parties</h2><p>Artwork Mockups uses infrastructure, storage and artificial-intelligence service providers to operate the features you request. Images and instructions may be sent to configured providers for processing. We limit this use to service delivery and apply provider and contractual controls appropriate to the deployment. Optional integrations are subject to the third party's own terms and policies.</p></section>
<section id="pinterest"><h2>4. Pinterest integration</h2><p>The Pinterest integration connects only after a user explicitly authorizes the official Artwork Mockups app. Artwork Mockups may then receive account identifiers, board information and information about Pins created through the platform. Each authorization token is encrypted and belongs only to the artist and Pinterest account that granted it.</p><p>This data is used exclusively to connect the artist's chosen Pinterest account, display available boards and publish Pins explicitly selected and approved by the user. Artist credentials are not reused for the Artwork Mockups platform identity or another artist. Artwork Mockups does not use Pinterest data for unrelated advertising, profiling or resale. Users may revoke access through Pinterest or disconnect it from Artwork Mockups at any time. On disconnection, stored Pinterest access credentials will be deleted or invalidated according to the system's retention and security rules.</p></section>
<section id="meta"><h2>5. Facebook and Instagram integration</h2><p>The optional Meta integration connects only after a user grants permission through Meta OAuth. Artwork Mockups may receive a Meta user identifier, the Pages available to that user, Page identifiers and names, a linked professional Instagram account identifier and username, granted permissions, token expiration information, encrypted access tokens, and identifiers or links for posts created through Artwork Mockups.</p><p>We use this information only to let the user select an authorized Page, prepare content and publish Facebook or Instagram posts that the user has separately reviewed and explicitly approved. We do not sell Meta Platform Data or use it for unrelated advertising or profiling. Users may disconnect locally or revoke access through Meta. See our <a href="<?= PublicPage::h(PublicPage::path('data-deletion/')) ?>">data deletion instructions</a> for removal options.</p></section>
<section id="retention"><h2>6. Retention and deletion</h2><p>We retain account and project data while an account is active and as reasonably needed to provide the service, resolve disputes, prevent abuse and satisfy legal obligations. Retention periods may vary by data type. You may request account and data deletion through the <a href="<?= PublicPage::h(PublicPage::path('contact/')) ?>">contact page</a> or follow our <a href="<?= PublicPage::h(PublicPage::path('data-deletion/')) ?>">data deletion instructions</a>. Some limited records may be retained where required for security, legal compliance or the establishment of legal claims.</p></section>
<section id="security"><h2>7. Security</h2><p>We use reasonable administrative and technical measures such as access controls, transport security, restricted credentials and activity monitoring. No online system can be guaranteed completely secure. Pinterest and Meta OAuth credentials are handled by the backend; access tokens are encrypted at rest and are not exposed in browser code.</p></section>
<section id="rights"><h2>8. Your choices and rights</h2><p>Depending on your location, you may have rights to access, correct, export, restrict or delete personal information, object to certain processing, or withdraw consent. Contact us to submit a request. We may need to verify your identity before acting on it.</p></section>
<section id="cookies"><h2>9. Essential cookies</h2><p>We use essential cookies or equivalent storage for authentication, session continuity, security and user preferences. These are necessary for core service operation. If optional analytics or marketing cookies are introduced, they will be described and managed separately where required.</p></section>
<section><h2>10. Changes and contact</h2><p>We may update this policy to reflect service, legal or security changes. The effective date above will be revised when material changes are published. For privacy requests, account deletion or questions, use our <a href="<?= PublicPage::h(PublicPage::path('contact/')) ?>">contact form</a>.</p></section>
<?php PublicPage::end(); ?>
