<?php
declare(strict_types=1);

$remote=(string)($_SERVER['REMOTE_ADDR']??'');
if(PHP_SAPI!=='cli'&&!in_array($remote,['127.0.0.1','::1'],true)){http_response_code(403);exit('Local preview only.');}
$file=__DIR__.'/data/drafts/artwork-sync-drafts.json';
$drafts=is_file($file)?json_decode((string)file_get_contents($file),true):[];
if(!is_array($drafts)||!$drafts){http_response_code(404);exit('No artwork sync drafts found.');}
$id=trim((string)($_GET['id']??''));
$draft=$id!==''?($drafts[$id]??null):end($drafts);
if(!is_array($draft)){http_response_code(404);exit('Draft not found.');}
$payload=(array)($draft['source_payload']??[]);$art=(array)($payload['artwork']??[]);$core=(array)($payload['editorial_core']??[]);$assets=(array)($payload['assets']??[]);$root=(array)($assets['artwork']??[]);$mockups=(array)($assets['mockups']??[]);
function dp_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function dp_media(string $draftId,string $assetId):string{return 'draft-media.php?'.http_build_query(['draft'=>$draftId,'asset'=>$assetId]);}
$dimensions=(array)($art['dimensions']??[]);$dimensionText=implode(' × ',array_filter([(string)($dimensions['width']??''),(string)($dimensions['height']??''),(string)($dimensions['depth']??'')],fn($v)=>$v!==''&&$v!=='0')).' '.(string)($dimensions['unit']??'');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=dp_h($art['title']??'Artwork')?> · Local Draft Preview</title><style>
:root{--paper:#f5f1eb;--ink:#171511;--muted:#746b60;--line:#d8d0c5;--accent:#9b6750}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}.preview-banner{padding:9px 5vw;background:#d8b7b5;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.page{max-width:1480px;margin:auto;padding:38px 5vw 80px}.hero{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(320px,.8fr);gap:48px;align-items:start}.hero img{display:block;width:100%;max-height:82vh;object-fit:contain;background:#ebe5dd}.eyebrow{color:var(--accent);font-size:11px;letter-spacing:.14em;text-transform:uppercase}h1{font-family:Georgia,serif;font-size:clamp(42px,6vw,78px);font-weight:400;line-height:.96;margin:14px 0 20px}.subtitle{font-family:Georgia,serif;font-size:22px;line-height:1.35}.summary{color:var(--muted);font-size:17px;line-height:1.7}.facts{display:grid;grid-template-columns:1fr 1fr;margin:26px 0;border-top:1px solid var(--line)}.facts div{padding:12px 0;border-bottom:1px solid var(--line)}.facts strong{display:block;color:var(--muted);font-size:10px;letter-spacing:.1em;text-transform:uppercase}.concept{max-width:820px;margin:70px auto;font-family:Georgia,serif;font-size:22px;line-height:1.65}.gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.gallery figure{margin:0}.gallery img{width:100%;aspect-ratio:4/5;object-fit:cover}.gallery figcaption{padding-top:8px;color:var(--muted);font-size:12px}.draft-meta{margin-top:50px;padding-top:18px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}@media(max-width:800px){.page{padding:20px 14px 60px}.hero{grid-template-columns:1fr;gap:24px}.gallery{grid-template-columns:1fr}.concept{margin:44px 0}.facts{grid-template-columns:1fr}}
</style></head><body><div class="preview-banner">Local preview · <?=dp_h(($draft['status']??'')==='published'?'published to local catalogue':'ready to publish')?> · content.json unchanged</div><main class="page"><section class="hero"><div><img src="<?=dp_h(dp_media((string)$draft['draft_id'],(string)($root['asset_id']??'')))?>" alt="<?=dp_h($core['alt_text']??$art['title']??'Artwork')?>"></div><div><span class="eyebrow"><?=dp_h($art['series']?:'Contemporary abstract painting')?></span><h1><?=dp_h($art['title']??'Untitled')?></h1><?php if(!empty($core['subtitle'])):?><p class="subtitle"><?=dp_h($core['subtitle'])?></p><?php endif;?><p class="summary"><?=dp_h($core['summary']??'')?></p><div class="facts"><div><strong>Year</strong><?=dp_h($art['year']??'')?></div><div><strong>Medium</strong><?=dp_h($art['medium']??'')?></div><div><strong>Dimensions</strong><?=dp_h($dimensionText)?></div><div><strong>Status</strong><?=dp_h(($draft['status']??'')==='published'?'Published':'Ready')?></div></div><p><?=dp_h($core['commercial_note']??'')?></p></div></section><section class="concept"><?=nl2br(dp_h($core['concept']??''))?></section><?php if($mockups):?><section><span class="eyebrow">Artwork in context</span><div class="gallery"><?php foreach($mockups as $mockup):?><figure><img src="<?=dp_h(dp_media((string)$draft['draft_id'],(string)($mockup['asset_id']??'')))?>" alt="<?=dp_h($mockup['alt_text']??'Artwork contextual mockup')?>"><figcaption><?=dp_h($mockup['caption']?:$mockup['title']?:'Context view')?></figcaption></figure><?php endforeach;?></div></section><?php endif;?><div class="draft-meta">Draft ID: <?=dp_h($draft['draft_id'])?> · Received <?=dp_h($draft['received_at']??'')?></div></main></body></html>
