<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/app/bootstrap.php';
$direction=$argv[1]??'up';$pdo=Database::connection();$mysql=Database::isMysql();
if($direction==='down'){$pdo->exec('DROP TABLE IF EXISTS pinterest_pin_drafts');echo "Pinterest Pin drafts table removed.\n";exit;}
if($direction!=='up')throw new InvalidArgumentException('Use up or down.');
if($mysql)$pdo->exec("CREATE TABLE IF NOT EXISTS pinterest_pin_drafts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,mockup_id INT UNSIGNED NOT NULL,purpose VARCHAR(20) NOT NULL DEFAULT 'artist',board_suggestion VARCHAR(255) NOT NULL DEFAULT '',board_id VARCHAR(190) NOT NULL DEFAULT '',board_name VARCHAR(255) NOT NULL DEFAULT '',title VARCHAR(100) NOT NULL DEFAULT '',description VARCHAR(500) NOT NULL DEFAULT '',alt_text VARCHAR(500) NOT NULL DEFAULT '',keywords MEDIUMTEXT NOT NULL,hashtags MEDIUMTEXT NOT NULL,destination_url MEDIUMTEXT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'draft',payload_json MEDIUMTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,KEY idx_pin_drafts_user_status(user_id,status),CONSTRAINT pin_drafts_user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT pin_drafts_mockup_fk FOREIGN KEY(mockup_id) REFERENCES mockups(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
else{$pdo->exec("CREATE TABLE IF NOT EXISTS pinterest_pin_drafts (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,mockup_id INTEGER NOT NULL,purpose TEXT NOT NULL DEFAULT 'artist',board_suggestion TEXT NOT NULL DEFAULT '',board_id TEXT NOT NULL DEFAULT '',board_name TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',alt_text TEXT NOT NULL DEFAULT '',keywords TEXT NOT NULL DEFAULT '',hashtags TEXT NOT NULL DEFAULT '',destination_url TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',payload_json TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(mockup_id) REFERENCES mockups(id) ON DELETE CASCADE)");$pdo->exec('CREATE INDEX IF NOT EXISTS idx_pin_drafts_user_status ON pinterest_pin_drafts(user_id,status)');}
echo "Pinterest Pin drafts table ready.\n";
