<?php
declare(strict_types=1);

require_once __DIR__ . '/../config.php';

if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
}
require_once __DIR__ . '/Support/Database.php';
require_once __DIR__ . '/Support/SchemaMigrator.php';
require_once __DIR__ . '/Support/AuthRateLimiter.php';
require_once __DIR__ . '/Support/Auth.php';
require_once __DIR__ . '/Support/RequestSecurity.php';
require_once __DIR__ . '/Support/FeatureAccess.php';
require_once __DIR__ . '/Support/UiPreview.php';
require_once __DIR__ . '/Support/ArtistProfile.php';
require_once __DIR__ . '/Support/ArtistDomainService.php';
require_once __DIR__ . '/Support/Display.php';
require_once __DIR__ . '/Support/PromptSettings.php';
require_once __DIR__ . '/Support/RootArtworkCropper.php';
require_once __DIR__ . '/Support/ManualArtworkFrameCropper.php';
require_once __DIR__ . '/Support/ProviderSettings.php';
require_once __DIR__ . '/Support/Logger.php';
require_once __DIR__ . '/Support/ImageResizer.php';
require_once __DIR__ . '/Support/ResponsiveImage.php';
require_once __DIR__ . '/Support/JsonStringNormalizer.php';
require_once __DIR__ . '/Support/ArtworkPhysicalIntegrityPolicy.php';
require_once __DIR__ . '/Support/SearchIntentPrompt.php';
require_once __DIR__ . '/Support/ArtworkAnalysisV2.php';
require_once __DIR__ . '/Support/ArtworkOriginalityChecker.php';
require_once __DIR__ . '/Support/DescriptionDiversityEngine.php';
require_once __DIR__ . '/Support/WorldMotherCameraAuthorityPolicy.php';
require_once __DIR__ . '/Support/MockupVariationEligibility.php';
require_once __DIR__ . '/Support/MockupFavorites.php';
require_once __DIR__ . '/Support/PublicArtistShowcase.php';
require_once __DIR__ . '/Support/StudioNoteEmbeddedImage.php';
require_once __DIR__ . '/Support/ArtworkSeries.php';
require_once __DIR__ . '/Support/AdminSceneEditor.php';
require_once __DIR__ . '/Support/PublicPage.php';
require_once __DIR__ . '/Support/ContactMessageRepository.php';
require_once __DIR__ . '/Services/ContactNotificationService.php';
require_once __DIR__ . '/Contracts/ArtworkProcessorInterface.php';
require_once __DIR__ . '/Contracts/MockupGeneratorInterface.php';
require_once __DIR__ . '/Services/MockupContextWorldRegistry.php';
require_once __DIR__ . '/Services/MockupWorldVisualPromptEnhancer.php';
require_once __DIR__ . '/Services/WorldMotherLibrary.php';
require_once __DIR__ . '/Services/WorldMotherGenerator.php';
require_once __DIR__ . '/Services/SceneRankingService.php';
require_once __DIR__ . '/Services/SceneReferenceDiversityService.php';
require_once __DIR__ . '/Services/StudioReferenceCatalog.php';
require_once __DIR__ . '/Services/CameraSlotStudio.php';
require_once __DIR__ . '/Services/ArtworkSheetService.php';
require_once __DIR__ . '/Services/ArtworkAnalysisV2Service.php';
require_once __DIR__ . '/Services/PublicationService.php';
require_once __DIR__ . '/Services/StudioNoteMediaService.php';
require_once __DIR__ . '/Services/WebsiteBoardService.php';
require_once __DIR__ . '/Services/ArtworkWebsiteDryRunService.php';
require_once __DIR__ . '/Services/ArtworkWebsiteV2Service.php';
require_once __DIR__ . '/Services/MockupEditorialContent.php';
require_once __DIR__ . '/Services/BilingualEditorialService.php';
require_once __DIR__ . '/Services/SeriesKeywordResearchService.php';
require_once __DIR__ . '/Services/MockupSocialContentService.php';
require_once __DIR__ . '/Services/MockupPinterestDraftService.php';
require_once __DIR__ . '/Services/MetaSocialDraftService.php';
require_once __DIR__ . '/Services/MetaIntegrationService.php';
require_once __DIR__ . '/Services/InstagramIntegrationService.php';
require_once __DIR__ . '/Services/MetaGraphClient.php';
require_once __DIR__ . '/Services/InstagramGraphClient.php';
require_once __DIR__ . '/Services/MetaPublisher.php';
require_once __DIR__ . '/Services/InstagramPublisher.php';
require_once __DIR__ . '/Services/MetaBatchService.php';
require_once __DIR__ . '/Services/PinterestPublisher.php';
require_once __DIR__ . '/Services/PinterestBatchService.php';
require_once __DIR__ . '/Services/PinterestIntegrationService.php';
require_once __DIR__ . '/Services/SocialCampaignPinterestBridge.php';
require_once __DIR__ . '/Services/SocialCampaignMetaBridge.php';
require_once __DIR__ . '/Services/SocialPublishJobService.php';
require_once __DIR__ . '/Services/SocialBoardPublishService.php';
require_once __DIR__ . '/Services/SocialScheduledPublicationService.php';
require_once __DIR__ . '/Services/ArtworkEmbeddingService.php';
require_once __DIR__ . '/Services/ArtworkGroupService.php';
require_once __DIR__ . '/Services/MockArtworkProcessor.php';
require_once __DIR__ . '/Services/MockMockupGenerator.php';
require_once __DIR__ . '/Services/MockupBatchQueue.php';
require_once __DIR__ . '/Services/GeminiImageClient.php';
require_once __DIR__ . '/Services/BilingualEditorialAdapterService.php';
require_once __DIR__ . '/Services/GeminiArtworkProcessor.php';
require_once __DIR__ . '/Services/GeminiMockupGenerator.php';
require_once __DIR__ . '/Services/ArtworkFidelityGate.php';
require_once __DIR__ . '/Services/FidelityValidatingMockupGenerator.php';
require_once __DIR__ . '/Services/OpenAIArtworkProcessor.php';
require_once __DIR__ . '/Services/OpenAIMockupGenerator.php';
require_once __DIR__ . '/Services/MockupPromptApprovalService.php';
require_once __DIR__ . '/Services/AdminPromptComposerPreview.php';
require_once __DIR__ . '/Services/MockupCombinationEngine.php';
require_once __DIR__ . '/Services/ServiceFactory.php';
require_once __DIR__ . '/Support/DatabaseSessionHandler.php';
require_once __DIR__ . '/Support/NextPlatformSync.php';
require_once __DIR__ . '/Services/CloudTasksService.php';
require_once __DIR__ . '/Services/StorageService.php';
require_once __DIR__ . '/Services/MockupGenerationWorker.php';
require_once __DIR__ . '/Services/MockupGenerationDispatcher.php';
require_once __DIR__ . '/Assistant/AssistantSchema.php';
require_once __DIR__ . '/Assistant/AssistantException.php';
require_once __DIR__ . '/Assistant/AssistantConfig.php';
require_once __DIR__ . '/Assistant/AssistantOpenAIClient.php';
require_once __DIR__ . '/Assistant/AssistantRepository.php';
require_once __DIR__ . '/Assistant/AssistantContext.php';
require_once __DIR__ . '/Assistant/AssistantService.php';
require_once __DIR__ . '/Assistant/AssistantView.php';

if (Database::isMysql()) {
    $handler = new DatabaseSessionHandler(Database::connection());
    session_set_save_handler($handler, true);
}

RequestSecurity::enforceMutationCsrf();
