<?php
declare(strict_types=1); require_once dirname(__DIR__) . '/app/bootstrap.php';
PublicPage::start('Terms of Service | Artwork Mockups','Review the terms governing the use of Artwork Mockups, uploaded artworks, generated mockups and third-party integrations.','terms/');
?>
<span class="eyebrow">Legal · Effective July 13, 2026</span><h1>Terms of Service</h1><p class="lede">These terms govern use of Artwork Mockups at artworkmockups.com. By creating an account or using the service, you agree to them.</p>
<nav class="toc" aria-label="Contents"><strong>Contents</strong><ol><li><a href="#service">Service</a></li><li><a href="#accounts">Accounts</a></li><li><a href="#content">Your content</a></li><li><a href="#use">Permitted use</a></li><li><a href="#third-parties">Third parties</a></li><li><a href="#pinterest">Pinterest</a></li><li><a href="#meta">Meta</a></li><li><a href="#availability">Availability</a></li><li><a href="#liability">Liability</a></li></ol></nav>
<section id="service"><h2>1. The service</h2><p>Artwork Mockups helps artists process images of original artwork and create photographic-style presentations and related publishing materials. Generated results may vary and should be reviewed before professional or public use.</p></section>
<section id="accounts"><h2>2. Eligibility and accounts</h2><p>You must be legally able to enter these terms and provide accurate account information. You are responsible for protecting your credentials and for activity under your account. Notify us promptly if you suspect unauthorized access.</p></section>
<section id="content"><h2>3. Artwork and intellectual property</h2><p>You retain rights in your original artwork and other content. You represent that you own or have permission to upload, process and publish all submitted content. You grant Artwork Mockups a limited, non-exclusive technical license to host, copy, transform and process that content only as needed to provide requested features, generate mockups, maintain backups and secure the service.</p><p>You may not upload another person's artwork or protected material without authorization. Generated mockups do not remove third-party rights that may exist in source content.</p></section>
<section id="use"><h2>4. Acceptable use</h2><p>Do not use the platform to violate law or rights, distribute malicious material, evade security, interfere with the service, impersonate others, mislead viewers, or create spam. We may investigate abuse and suspend or terminate accounts where reasonably necessary to protect users, third parties or the platform.</p></section>
<section id="third-parties"><h2>5. Third-party services</h2><p>Some features depend on infrastructure, AI or publishing services operated by third parties. Their availability and handling of data are also governed by their own terms and policies. Artwork Mockups is not responsible for changes or outages in services it does not control.</p></section>
<section id="pinterest"><h2>6. Pinterest</h2><p>Pinterest is a third-party service governed by its own terms and policies. Artwork Mockups does not control the availability, moderation, distribution or removal of Pins by Pinterest.</p><p>You are responsible for reviewing and explicitly approving each image, board, title, description and destination link before publication. Artwork Mockups must not be used for automated spam, mass publishing or misleading content. Pinterest access may be disconnected or revoked at any time by you, Pinterest or Artwork Mockups where necessary.</p></section>
<section id="meta"><h2>7. Facebook and Instagram</h2><p>Facebook and Instagram are third-party services operated by Meta and governed by Meta's terms and policies. Artwork Mockups does not control their availability, moderation, distribution or removal decisions.</p><p>You are responsible for selecting the correct Page and professional Instagram account and for reviewing each image, caption, hashtag, alt text and destination before explicitly approving publication. Do not use the integration for spam, deceptive content or unauthorized accounts. Meta access may be disconnected or revoked at any time by you, Meta or Artwork Mockups where necessary.</p></section>
<section id="availability"><h2>8. Availability, changes and termination</h2><p>We may maintain, modify or discontinue features and cannot promise uninterrupted or error-free operation. You may request account deletion through the contact page. We may retain limited records as described in the Privacy Policy. We may suspend access for abuse, security risk, non-payment where applicable or material breach of these terms.</p></section>
<section id="liability"><h2>9. Disclaimers and reasonable limitation</h2><p>The service is provided on an “as available” basis to the extent permitted by law. You remain responsible for reviewing outputs and publications. To the maximum extent permitted by applicable law, Artwork Mockups is not liable for indirect, incidental, special or consequential losses, loss of profits or data, or third-party platform decisions. Nothing in these terms excludes liability that cannot legally be excluded.</p></section>
<section><h2>10. Contact</h2><p>Questions about these terms, copyright matters or account deletion can be submitted through the <a href="<?= PublicPage::h(PublicPage::path('contact/')) ?>">Artwork Mockups contact page</a>.</p></section>
<?php PublicPage::end(); ?>
